// Generated from QMK qmk_firmware master:
// - quantum/keycodes.h
// - data/constants/keycodes/*.hjson
// Regenerate by rerunning the local Codex QMK metadata generation step.

export type QmkKeycodeInfo = {
  key: string;
  label: string;
  aliases: readonly string[];
  group?: string;
};

export const qmkDirectKeycodes: Record<number, QmkKeycodeInfo> = {
  0x0000: { key: "KC_NO", label: "N/A", aliases: ["XXXXXXX"], group: "internal" },
  0x0001: {
    key: "KC_TRANSPARENT",
    label: "Transparent",
    aliases: ["KC_TRNS", "_______"],
    group: "internal",
  },
  0x0004: { key: "KC_A", label: "A", aliases: [], group: "basic" },
  0x0005: { key: "KC_B", label: "B", aliases: [], group: "basic" },
  0x0006: { key: "KC_C", label: "C", aliases: [], group: "basic" },
  0x0007: { key: "KC_D", label: "D", aliases: [], group: "basic" },
  0x0008: { key: "KC_E", label: "E", aliases: [], group: "basic" },
  0x0009: { key: "KC_F", label: "F", aliases: [], group: "basic" },
  0x000a: { key: "KC_G", label: "G", aliases: [], group: "basic" },
  0x000b: { key: "KC_H", label: "H", aliases: [], group: "basic" },
  0x000c: { key: "KC_I", label: "I", aliases: [], group: "basic" },
  0x000d: { key: "KC_J", label: "J", aliases: [], group: "basic" },
  0x000e: { key: "KC_K", label: "K", aliases: [], group: "basic" },
  0x000f: { key: "KC_L", label: "L", aliases: [], group: "basic" },
  0x0010: { key: "KC_M", label: "M", aliases: [], group: "basic" },
  0x0011: { key: "KC_N", label: "N", aliases: [], group: "basic" },
  0x0012: { key: "KC_O", label: "O", aliases: [], group: "basic" },
  0x0013: { key: "KC_P", label: "P", aliases: [], group: "basic" },
  0x0014: { key: "KC_Q", label: "Q", aliases: [], group: "basic" },
  0x0015: { key: "KC_R", label: "R", aliases: [], group: "basic" },
  0x0016: { key: "KC_S", label: "S", aliases: [], group: "basic" },
  0x0017: { key: "KC_T", label: "T", aliases: [], group: "basic" },
  0x0018: { key: "KC_U", label: "U", aliases: [], group: "basic" },
  0x0019: { key: "KC_V", label: "V", aliases: [], group: "basic" },
  0x001a: { key: "KC_W", label: "W", aliases: [], group: "basic" },
  0x001b: { key: "KC_X", label: "X", aliases: [], group: "basic" },
  0x001c: { key: "KC_Y", label: "Y", aliases: [], group: "basic" },
  0x001d: { key: "KC_Z", label: "Z", aliases: [], group: "basic" },
  0x001e: { key: "KC_1", label: "1", aliases: [], group: "basic" },
  0x001f: { key: "KC_2", label: "2", aliases: [], group: "basic" },
  0x0020: { key: "KC_3", label: "3", aliases: [], group: "basic" },
  0x0021: { key: "KC_4", label: "4", aliases: [], group: "basic" },
  0x0022: { key: "KC_5", label: "5", aliases: [], group: "basic" },
  0x0023: { key: "KC_6", label: "6", aliases: [], group: "basic" },
  0x0024: { key: "KC_7", label: "7", aliases: [], group: "basic" },
  0x0025: { key: "KC_8", label: "8", aliases: [], group: "basic" },
  0x0026: { key: "KC_9", label: "9", aliases: [], group: "basic" },
  0x0027: { key: "KC_0", label: "0", aliases: [], group: "basic" },
  0x0028: { key: "KC_ENTER", label: "Enter", aliases: ["KC_ENT"], group: "basic" },
  0x0029: { key: "KC_ESCAPE", label: "Esc", aliases: ["KC_ESC"], group: "basic" },
  0x002a: { key: "KC_BACKSPACE", label: "Backspace", aliases: ["KC_BSPC"], group: "basic" },
  0x002b: { key: "KC_TAB", label: "Tab", aliases: [], group: "basic" },
  0x002c: { key: "KC_SPACE", label: "Spacebar", aliases: ["KC_SPC"], group: "basic" },
  0x002d: { key: "KC_MINUS", label: "-", aliases: ["KC_MINS"], group: "basic" },
  0x002e: { key: "KC_EQUAL", label: "=", aliases: ["KC_EQL"], group: "basic" },
  0x002f: { key: "KC_LEFT_BRACKET", label: "[", aliases: ["KC_LBRC"], group: "basic" },
  0x0030: { key: "KC_RIGHT_BRACKET", label: "]", aliases: ["KC_RBRC"], group: "basic" },
  0x0031: { key: "KC_BACKSLASH", label: "\\\\", aliases: ["KC_BSLS"], group: "basic" },
  0x0032: { key: "KC_NONUS_HASH", label: "#", aliases: ["KC_NUHS"], group: "basic" },
  0x0033: { key: "KC_SEMICOLON", label: ";", aliases: ["KC_SCLN"], group: "basic" },
  0x0034: { key: "KC_QUOTE", label: "'", aliases: ["KC_QUOT"], group: "basic" },
  0x0035: { key: "KC_GRAVE", label: "`", aliases: ["KC_GRV"], group: "basic" },
  0x0036: { key: "KC_COMMA", label: ",", aliases: ["KC_COMM"], group: "basic" },
  0x0037: { key: "KC_DOT", label: ".", aliases: [], group: "basic" },
  0x0038: { key: "KC_SLASH", label: "/", aliases: ["KC_SLSH"], group: "basic" },
  0x0039: { key: "KC_CAPS_LOCK", label: "Caps Lock", aliases: ["KC_CAPS"], group: "basic" },
  0x003a: { key: "KC_F1", label: "F1", aliases: [], group: "basic" },
  0x003b: { key: "KC_F2", label: "F2", aliases: [], group: "basic" },
  0x003c: { key: "KC_F3", label: "F3", aliases: [], group: "basic" },
  0x003d: { key: "KC_F4", label: "F4", aliases: [], group: "basic" },
  0x003e: { key: "KC_F5", label: "F5", aliases: [], group: "basic" },
  0x003f: { key: "KC_F6", label: "F6", aliases: [], group: "basic" },
  0x0040: { key: "KC_F7", label: "F7", aliases: [], group: "basic" },
  0x0041: { key: "KC_F8", label: "F8", aliases: [], group: "basic" },
  0x0042: { key: "KC_F9", label: "F9", aliases: [], group: "basic" },
  0x0043: { key: "KC_F10", label: "F10", aliases: [], group: "basic" },
  0x0044: { key: "KC_F11", label: "F11", aliases: [], group: "basic" },
  0x0045: { key: "KC_F12", label: "F12", aliases: [], group: "basic" },
  0x0046: { key: "KC_PRINT_SCREEN", label: "Print Screen", aliases: ["KC_PSCR"], group: "basic" },
  0x0047: {
    key: "KC_SCROLL_LOCK",
    label: "Scroll Lock",
    aliases: ["KC_BRMD", "KC_SCRL"],
    group: "basic",
  },
  0x0048: {
    key: "KC_PAUSE",
    label: "Pause",
    aliases: ["KC_BRK", "KC_BRMU", "KC_PAUS"],
    group: "basic",
  },
  0x0049: { key: "KC_INSERT", label: "Insert", aliases: ["KC_INS"], group: "basic" },
  0x004a: { key: "KC_HOME", label: "Home", aliases: [], group: "basic" },
  0x004b: { key: "KC_PAGE_UP", label: "Page Up", aliases: ["KC_PGUP"], group: "basic" },
  0x004c: { key: "KC_DELETE", label: "Delete", aliases: ["KC_DEL"], group: "basic" },
  0x004d: { key: "KC_END", label: "End", aliases: [], group: "basic" },
  0x004e: { key: "KC_PAGE_DOWN", label: "Page Down", aliases: ["KC_PGDN"], group: "basic" },
  0x004f: { key: "KC_RIGHT", label: "Right", aliases: ["KC_RGHT"], group: "basic" },
  0x0050: { key: "KC_LEFT", label: "Left", aliases: [], group: "basic" },
  0x0051: { key: "KC_DOWN", label: "Down", aliases: [], group: "basic" },
  0x0052: { key: "KC_UP", label: "Up", aliases: [], group: "basic" },
  0x0053: { key: "KC_NUM_LOCK", label: "Num Lock", aliases: ["KC_NUM"], group: "basic" },
  0x0054: { key: "KC_KP_SLASH", label: "/", aliases: ["KC_PSLS"], group: "basic" },
  0x0055: { key: "KC_KP_ASTERISK", label: "*", aliases: ["KC_PAST"], group: "basic" },
  0x0056: { key: "KC_KP_MINUS", label: "-", aliases: ["KC_PMNS"], group: "basic" },
  0x0057: { key: "KC_KP_PLUS", label: "+", aliases: ["KC_PPLS"], group: "basic" },
  0x0058: { key: "KC_KP_ENTER", label: "Enter", aliases: ["KC_PENT"], group: "basic" },
  0x0059: { key: "KC_KP_1", label: "1", aliases: ["KC_P1"], group: "basic" },
  0x005a: { key: "KC_KP_2", label: "2", aliases: ["KC_P2"], group: "basic" },
  0x005b: { key: "KC_KP_3", label: "3", aliases: ["KC_P3"], group: "basic" },
  0x005c: { key: "KC_KP_4", label: "4", aliases: ["KC_P4"], group: "basic" },
  0x005d: { key: "KC_KP_5", label: "5", aliases: ["KC_P5"], group: "basic" },
  0x005e: { key: "KC_KP_6", label: "6", aliases: ["KC_P6"], group: "basic" },
  0x005f: { key: "KC_KP_7", label: "7", aliases: ["KC_P7"], group: "basic" },
  0x0060: { key: "KC_KP_8", label: "8", aliases: ["KC_P8"], group: "basic" },
  0x0061: { key: "KC_KP_9", label: "9", aliases: ["KC_P9"], group: "basic" },
  0x0062: { key: "KC_KP_0", label: "0", aliases: ["KC_P0"], group: "basic" },
  0x0063: { key: "KC_KP_DOT", label: ".", aliases: ["KC_PDOT"], group: "basic" },
  0x0064: { key: "KC_NONUS_BACKSLASH", label: "\\\\", aliases: ["KC_NUBS"], group: "basic" },
  0x0065: { key: "KC_APPLICATION", label: "App", aliases: ["KC_APP"], group: "basic" },
  0x0066: { key: "KC_KB_POWER", label: "Power", aliases: [], group: "basic" },
  0x0067: { key: "KC_KP_EQUAL", label: "=", aliases: ["KC_PEQL"], group: "basic" },
  0x0068: { key: "KC_F13", label: "F13", aliases: [], group: "basic" },
  0x0069: { key: "KC_F14", label: "F14", aliases: [], group: "basic" },
  0x006a: { key: "KC_F15", label: "F15", aliases: [], group: "basic" },
  0x006b: { key: "KC_F16", label: "F16", aliases: [], group: "basic" },
  0x006c: { key: "KC_F17", label: "F17", aliases: [], group: "basic" },
  0x006d: { key: "KC_F18", label: "F18", aliases: [], group: "basic" },
  0x006e: { key: "KC_F19", label: "F19", aliases: [], group: "basic" },
  0x006f: { key: "KC_F20", label: "F20", aliases: [], group: "basic" },
  0x0070: { key: "KC_F21", label: "F21", aliases: [], group: "basic" },
  0x0071: { key: "KC_F22", label: "F22", aliases: [], group: "basic" },
  0x0072: { key: "KC_F23", label: "F23", aliases: [], group: "basic" },
  0x0073: { key: "KC_F24", label: "F24", aliases: [], group: "basic" },
  0x0074: { key: "KC_EXECUTE", label: "Execute", aliases: ["KC_EXEC"], group: "basic" },
  0x0075: { key: "KC_HELP", label: "Help", aliases: [], group: "basic" },
  0x0076: { key: "KC_MENU", label: "Menu", aliases: [], group: "basic" },
  0x0077: { key: "KC_SELECT", label: "Select", aliases: ["KC_SLCT"], group: "basic" },
  0x0078: { key: "KC_STOP", label: "Stop", aliases: [], group: "basic" },
  0x0079: { key: "KC_AGAIN", label: "Again", aliases: ["KC_AGIN"], group: "basic" },
  0x007a: { key: "KC_UNDO", label: "Undo", aliases: [], group: "basic" },
  0x007b: { key: "KC_CUT", label: "Cut", aliases: [], group: "basic" },
  0x007c: { key: "KC_COPY", label: "Copy", aliases: [], group: "basic" },
  0x007d: { key: "KC_PASTE", label: "Paste", aliases: ["KC_PSTE"], group: "basic" },
  0x007e: { key: "KC_FIND", label: "Find", aliases: [], group: "basic" },
  0x007f: { key: "KC_KB_MUTE", label: "Mute", aliases: [], group: "basic" },
  0x0080: { key: "KC_KB_VOLUME_UP", label: "Volume Up", aliases: [], group: "basic" },
  0x0081: { key: "KC_KB_VOLUME_DOWN", label: "Volume Down", aliases: [], group: "basic" },
  0x0082: { key: "KC_LOCKING_CAPS_LOCK", label: "Caps Lock", aliases: ["KC_LCAP"], group: "basic" },
  0x0083: { key: "KC_LOCKING_NUM_LOCK", label: "Num Lock", aliases: ["KC_LNUM"], group: "basic" },
  0x0084: {
    key: "KC_LOCKING_SCROLL_LOCK",
    label: "Scroll Lock",
    aliases: ["KC_LSCR"],
    group: "basic",
  },
  0x0085: { key: "KC_KP_COMMA", label: ",", aliases: ["KC_PCMM"], group: "basic" },
  0x0086: { key: "KC_KP_EQUAL_AS400", label: "=", aliases: [], group: "basic" },
  0x0087: { key: "KC_INTERNATIONAL_1", label: "INT 1", aliases: ["KC_INT1"], group: "basic" },
  0x0088: { key: "KC_INTERNATIONAL_2", label: "INT 2", aliases: ["KC_INT2"], group: "basic" },
  0x0089: { key: "KC_INTERNATIONAL_3", label: "INT 3", aliases: ["KC_INT3"], group: "basic" },
  0x008a: { key: "KC_INTERNATIONAL_4", label: "INT 4", aliases: ["KC_INT4"], group: "basic" },
  0x008b: { key: "KC_INTERNATIONAL_5", label: "INT 5", aliases: ["KC_INT5"], group: "basic" },
  0x008c: { key: "KC_INTERNATIONAL_6", label: "INT 6", aliases: ["KC_INT6"], group: "basic" },
  0x008d: { key: "KC_INTERNATIONAL_7", label: "INT 7", aliases: ["KC_INT7"], group: "basic" },
  0x008e: { key: "KC_INTERNATIONAL_8", label: "INT 8", aliases: ["KC_INT8"], group: "basic" },
  0x008f: { key: "KC_INTERNATIONAL_9", label: "INT 9", aliases: ["KC_INT9"], group: "basic" },
  0x0090: { key: "KC_LANGUAGE_1", label: "LANG 1", aliases: ["KC_LNG1"], group: "basic" },
  0x0091: { key: "KC_LANGUAGE_2", label: "LANG 2", aliases: ["KC_LNG2"], group: "basic" },
  0x0092: { key: "KC_LANGUAGE_3", label: "LANG 3", aliases: ["KC_LNG3"], group: "basic" },
  0x0093: { key: "KC_LANGUAGE_4", label: "LANG 4", aliases: ["KC_LNG4"], group: "basic" },
  0x0094: { key: "KC_LANGUAGE_5", label: "LANG 5", aliases: ["KC_LNG5"], group: "basic" },
  0x0095: { key: "KC_LANGUAGE_6", label: "LANG 6", aliases: ["KC_LNG6"], group: "basic" },
  0x0096: { key: "KC_LANGUAGE_7", label: "LANG 7", aliases: ["KC_LNG7"], group: "basic" },
  0x0097: { key: "KC_LANGUAGE_8", label: "LANG 8", aliases: ["KC_LNG8"], group: "basic" },
  0x0098: { key: "KC_LANGUAGE_9", label: "LANG 9", aliases: ["KC_LNG9"], group: "basic" },
  0x0099: {
    key: "KC_ALTERNATE_ERASE",
    label: "Alternate Erase",
    aliases: ["KC_ERAS"],
    group: "basic",
  },
  0x009a: {
    key: "KC_SYSTEM_REQUEST",
    label: "SysReq/Attention",
    aliases: ["KC_SYRQ"],
    group: "basic",
  },
  0x009b: { key: "KC_CANCEL", label: "Cancel", aliases: ["KC_CNCL"], group: "basic" },
  0x009c: { key: "KC_CLEAR", label: "Clear", aliases: ["KC_CLR"], group: "basic" },
  0x009d: { key: "KC_PRIOR", label: "Prior", aliases: ["KC_PRIR"], group: "basic" },
  0x009e: { key: "KC_RETURN", label: "Return", aliases: ["KC_RETN"], group: "basic" },
  0x009f: { key: "KC_SEPARATOR", label: "Separator", aliases: ["KC_SEPR"], group: "basic" },
  0x00a0: { key: "KC_OUT", label: "Out", aliases: [], group: "basic" },
  0x00a1: { key: "KC_OPER", label: "Oper", aliases: [], group: "basic" },
  0x00a2: { key: "KC_CLEAR_AGAIN", label: "Clear/Again", aliases: ["KC_CLAG"], group: "basic" },
  0x00a3: { key: "KC_CRSEL", label: "CrSel/Props", aliases: ["KC_CRSL"], group: "basic" },
  0x00a4: { key: "KC_EXSEL", label: "ExSel", aliases: ["KC_EXSL"], group: "basic" },
  0x00a5: { key: "KC_SYSTEM_POWER", label: "Power", aliases: ["KC_PWR"], group: "system" },
  0x00a6: { key: "KC_SYSTEM_SLEEP", label: "Sleep", aliases: ["KC_SLEP"], group: "system" },
  0x00a7: { key: "KC_SYSTEM_WAKE", label: "Wake", aliases: ["KC_WAKE"], group: "system" },
  0x00a8: { key: "KC_AUDIO_MUTE", label: "Mute", aliases: ["KC_MUTE"], group: "media" },
  0x00a9: { key: "KC_AUDIO_VOL_UP", label: "Volume Up", aliases: ["KC_VOLU"], group: "media" },
  0x00aa: { key: "KC_AUDIO_VOL_DOWN", label: "Volume Down", aliases: ["KC_VOLD"], group: "media" },
  0x00ab: { key: "KC_MEDIA_NEXT_TRACK", label: "Next", aliases: ["KC_MNXT"], group: "media" },
  0x00ac: { key: "KC_MEDIA_PREV_TRACK", label: "Previous", aliases: ["KC_MPRV"], group: "media" },
  0x00ad: { key: "KC_MEDIA_STOP", label: "Stop", aliases: ["KC_MSTP"], group: "media" },
  0x00ae: { key: "KC_MEDIA_PLAY_PAUSE", label: "Play/Pause", aliases: ["KC_MPLY"], group: "media" },
  0x00af: { key: "KC_MEDIA_SELECT", label: "Media", aliases: ["KC_MSEL"], group: "media" },
  0x00b0: { key: "KC_MEDIA_EJECT", label: "Eject", aliases: ["KC_EJCT"], group: "media" },
  0x00b1: { key: "KC_MAIL", label: "Mail", aliases: [], group: "media" },
  0x00b2: { key: "KC_CALCULATOR", label: "Calculator", aliases: ["KC_CALC"], group: "media" },
  0x00b3: { key: "KC_MY_COMPUTER", label: "My Computer", aliases: ["KC_MYCM"], group: "media" },
  0x00b4: { key: "KC_WWW_SEARCH", label: "Search", aliases: ["KC_WSCH"], group: "media" },
  0x00b5: { key: "KC_WWW_HOME", label: "Home", aliases: ["KC_WHOM"], group: "media" },
  0x00b6: { key: "KC_WWW_BACK", label: "Back", aliases: ["KC_WBAK"], group: "media" },
  0x00b7: { key: "KC_WWW_FORWARD", label: "Forward", aliases: ["KC_WFWD"], group: "media" },
  0x00b8: { key: "KC_WWW_STOP", label: "Stop", aliases: ["KC_WSTP"], group: "media" },
  0x00b9: { key: "KC_WWW_REFRESH", label: "Refresh", aliases: ["KC_WREF"], group: "media" },
  0x00ba: { key: "KC_WWW_FAVORITES", label: "Favorites", aliases: ["KC_WFAV"], group: "media" },
  0x00bb: {
    key: "KC_MEDIA_FAST_FORWARD",
    label: "Fast Forward",
    aliases: ["KC_MFFD"],
    group: "media",
  },
  0x00bc: { key: "KC_MEDIA_REWIND", label: "Rewind", aliases: ["KC_MRWD"], group: "media" },
  0x00bd: { key: "KC_BRIGHTNESS_UP", label: "Brightness Up", aliases: ["KC_BRIU"], group: "media" },
  0x00be: {
    key: "KC_BRIGHTNESS_DOWN",
    label: "Brightness Down",
    aliases: ["KC_BRID"],
    group: "media",
  },
  0x00bf: { key: "KC_CONTROL_PANEL", label: "Control Panel", aliases: ["KC_CPNL"], group: "media" },
  0x00c0: { key: "KC_ASSISTANT", label: "Assistant", aliases: ["KC_ASST"], group: "media" },
  0x00c1: {
    key: "KC_MISSION_CONTROL",
    label: "Mission Control",
    aliases: ["KC_MCTL"],
    group: "media",
  },
  0x00c2: { key: "KC_LAUNCHPAD", label: "Launchpad", aliases: ["KC_LPAD"], group: "media" },
  0x00cd: {
    key: "QK_MOUSE_CURSOR_UP",
    label: "Mouse Up",
    aliases: ["!reset!", "MS_UP"],
    group: "mouse",
  },
  0x00ce: {
    key: "QK_MOUSE_CURSOR_DOWN",
    label: "Mouse Down",
    aliases: ["!reset!", "MS_DOWN"],
    group: "mouse",
  },
  0x00cf: {
    key: "QK_MOUSE_CURSOR_LEFT",
    label: "Mouse Left",
    aliases: ["!reset!", "MS_LEFT"],
    group: "mouse",
  },
  0x00d0: {
    key: "QK_MOUSE_CURSOR_RIGHT",
    label: "Mouse Right",
    aliases: ["!reset!", "MS_RGHT"],
    group: "mouse",
  },
  0x00d1: {
    key: "QK_MOUSE_BUTTON_1",
    label: "Mouse Button 1",
    aliases: ["!reset!", "MS_BTN1"],
    group: "mouse",
  },
  0x00d2: {
    key: "QK_MOUSE_BUTTON_2",
    label: "Mouse Button 2",
    aliases: ["!reset!", "MS_BTN2"],
    group: "mouse",
  },
  0x00d3: {
    key: "QK_MOUSE_BUTTON_3",
    label: "Mouse Button 3",
    aliases: ["!reset!", "MS_BTN3"],
    group: "mouse",
  },
  0x00d4: {
    key: "QK_MOUSE_BUTTON_4",
    label: "Mouse Button 4",
    aliases: ["!reset!", "MS_BTN4"],
    group: "mouse",
  },
  0x00d5: {
    key: "QK_MOUSE_BUTTON_5",
    label: "Mouse Button 5",
    aliases: ["!reset!", "MS_BTN5"],
    group: "mouse",
  },
  0x00d6: {
    key: "QK_MOUSE_BUTTON_6",
    label: "Mouse Button 6",
    aliases: ["!reset!", "MS_BTN6"],
    group: "mouse",
  },
  0x00d7: {
    key: "QK_MOUSE_BUTTON_7",
    label: "Mouse Button 7",
    aliases: ["!reset!", "MS_BTN7"],
    group: "mouse",
  },
  0x00d8: {
    key: "QK_MOUSE_BUTTON_8",
    label: "Mouse Button 8",
    aliases: ["!reset!", "MS_BTN8"],
    group: "mouse",
  },
  0x00d9: {
    key: "QK_MOUSE_WHEEL_UP",
    label: "Mouse Wheel Up",
    aliases: ["!reset!", "MS_WHLU"],
    group: "mouse",
  },
  0x00da: {
    key: "QK_MOUSE_WHEEL_DOWN",
    label: "Mouse Wheel Down",
    aliases: ["!reset!", "MS_WHLD"],
    group: "mouse",
  },
  0x00db: {
    key: "QK_MOUSE_WHEEL_LEFT",
    label: "Mouse Wheel Left",
    aliases: ["!reset!", "MS_WHLL"],
    group: "mouse",
  },
  0x00dc: {
    key: "QK_MOUSE_WHEEL_RIGHT",
    label: "Mouse Wheel Right",
    aliases: ["!reset!", "MS_WHLR"],
    group: "mouse",
  },
  0x00dd: {
    key: "QK_MOUSE_ACCELERATION_0",
    label: "Acceleration 0",
    aliases: ["!reset!", "MS_ACL0"],
    group: "mouse",
  },
  0x00de: {
    key: "QK_MOUSE_ACCELERATION_1",
    label: "Acceleration 1",
    aliases: ["!reset!", "MS_ACL1"],
    group: "mouse",
  },
  0x00df: {
    key: "QK_MOUSE_ACCELERATION_2",
    label: "Acceleration 2",
    aliases: ["!reset!", "MS_ACL2"],
    group: "mouse",
  },
  0x00e0: { key: "KC_LEFT_CTRL", label: "Left Control", aliases: ["KC_LCTL"], group: "modifiers" },
  0x00e1: { key: "KC_LEFT_SHIFT", label: "Left Shift", aliases: ["KC_LSFT"], group: "modifiers" },
  0x00e2: {
    key: "KC_LEFT_ALT",
    label: "Left Alt",
    aliases: ["KC_LALT", "KC_LOPT"],
    group: "modifiers",
  },
  0x00e3: {
    key: "KC_LEFT_GUI",
    label: "Left GUI",
    aliases: ["KC_LCMD", "KC_LGUI", "KC_LWIN"],
    group: "modifiers",
  },
  0x00e4: {
    key: "KC_RIGHT_CTRL",
    label: "Right Control",
    aliases: ["KC_RCTL"],
    group: "modifiers",
  },
  0x00e5: { key: "KC_RIGHT_SHIFT", label: "Right Shift", aliases: ["KC_RSFT"], group: "modifiers" },
  0x00e6: {
    key: "KC_RIGHT_ALT",
    label: "Right Alt",
    aliases: ["KC_ALGR", "KC_RALT", "KC_ROPT"],
    group: "modifiers",
  },
  0x00e7: {
    key: "KC_RIGHT_GUI",
    label: "Right GUI",
    aliases: ["KC_RCMD", "KC_RGUI", "KC_RWIN"],
    group: "modifiers",
  },
  0x56f0: {
    key: "QK_SWAP_HANDS_TOGGLE",
    label: "Toggle Swap Hands",
    aliases: ["SH_TOGG"],
    group: "swap_hands",
  },
  0x56f1: {
    key: "QK_SWAP_HANDS_TAP_TOGGLE",
    label: "Swap Hands Tap Toggle",
    aliases: ["SH_TT"],
    group: "swap_hands",
  },
  0x56f2: {
    key: "QK_SWAP_HANDS_MOMENTARY_ON",
    label: "Swap Hands Momentary On",
    aliases: ["SH_MON"],
    group: "swap_hands",
  },
  0x56f3: {
    key: "QK_SWAP_HANDS_MOMENTARY_OFF",
    label: "Swap Hands Momentary Off",
    aliases: ["SH_MOFF"],
    group: "swap_hands",
  },
  0x56f4: {
    key: "QK_SWAP_HANDS_OFF",
    label: "Unswap Hands",
    aliases: ["SH_OFF"],
    group: "swap_hands",
  },
  0x56f5: { key: "QK_SWAP_HANDS_ON", label: "Swap Hands", aliases: ["SH_ON"], group: "swap_hands" },
  0x56f6: {
    key: "QK_SWAP_HANDS_ONE_SHOT",
    label: "Swap Hands One Shot",
    aliases: ["SH_OS"],
    group: "swap_hands",
  },
  0x7000: {
    key: "QK_MAGIC_SWAP_CONTROL_CAPS_LOCK",
    label: "Swap LCtl\u21c4Caps",
    aliases: ["CL_SWAP"],
    group: "magic",
  },
  0x7001: {
    key: "QK_MAGIC_UNSWAP_CONTROL_CAPS_LOCK",
    label: "Unswap LCtl\u21c4Caps",
    aliases: ["CL_NORM"],
    group: "magic",
  },
  0x7002: {
    key: "QK_MAGIC_TOGGLE_CONTROL_CAPS_LOCK",
    label: "Toggle LCtl\u21c4Caps",
    aliases: ["CL_TOGG"],
    group: "magic",
  },
  0x7003: {
    key: "QK_MAGIC_CAPS_LOCK_AS_CONTROL_OFF",
    label: "Caps\u2260LCtl",
    aliases: ["CL_CAPS"],
    group: "magic",
  },
  0x7004: {
    key: "QK_MAGIC_CAPS_LOCK_AS_CONTROL_ON",
    label: "Caps=LCtl",
    aliases: ["CL_CTRL"],
    group: "magic",
  },
  0x7005: {
    key: "QK_MAGIC_SWAP_LALT_LGUI",
    label: "Swap LAlt\u21c4LGUI",
    aliases: ["AG_LSWP"],
    group: "magic",
  },
  0x7006: {
    key: "QK_MAGIC_UNSWAP_LALT_LGUI",
    label: "Unswap LAlt\u21c4LGUI",
    aliases: ["AG_LNRM"],
    group: "magic",
  },
  0x7007: {
    key: "QK_MAGIC_SWAP_RALT_RGUI",
    label: "Swap RAlt\u21c4RGUI",
    aliases: ["AG_RSWP"],
    group: "magic",
  },
  0x7008: {
    key: "QK_MAGIC_UNSWAP_RALT_RGUI",
    label: "Unswap RAlt\u21c4RGUI",
    aliases: ["AG_RNRM"],
    group: "magic",
  },
  0x7009: { key: "QK_MAGIC_GUI_ON", label: "GUI On", aliases: ["GU_ON"], group: "magic" },
  0x700a: { key: "QK_MAGIC_GUI_OFF", label: "GUI Off", aliases: ["GU_OFF"], group: "magic" },
  0x700b: { key: "QK_MAGIC_TOGGLE_GUI", label: "Toggle GUI", aliases: ["GU_TOGG"], group: "magic" },
  0x700c: {
    key: "QK_MAGIC_SWAP_GRAVE_ESC",
    label: "Swap `\u21c4Esc",
    aliases: ["GE_SWAP"],
    group: "magic",
  },
  0x700d: {
    key: "QK_MAGIC_UNSWAP_GRAVE_ESC",
    label: "Unswap `\u21c4Esc",
    aliases: ["GE_NORM"],
    group: "magic",
  },
  0x700e: {
    key: "QK_MAGIC_SWAP_BACKSLASH_BACKSPACE",
    label: "Swap \\\\\u21c4Bspc",
    aliases: ["BS_SWAP"],
    group: "magic",
  },
  0x700f: {
    key: "QK_MAGIC_UNSWAP_BACKSLASH_BACKSPACE",
    label: "Unswap \\\\\u21c4Bspc",
    aliases: ["BS_NORM"],
    group: "magic",
  },
  0x7010: {
    key: "QK_MAGIC_TOGGLE_BACKSLASH_BACKSPACE",
    label: "Toggle \\\\\u21c4Bspc",
    aliases: ["BS_TOGG"],
    group: "magic",
  },
  0x7011: { key: "QK_MAGIC_NKRO_ON", label: "NKRO On", aliases: ["NK_ON"], group: "magic" },
  0x7012: { key: "QK_MAGIC_NKRO_OFF", label: "NKRO Off", aliases: ["NK_OFF"], group: "magic" },
  0x7013: {
    key: "QK_MAGIC_TOGGLE_NKRO",
    label: "Toggle NKRO",
    aliases: ["NK_TOGG"],
    group: "magic",
  },
  0x7014: {
    key: "QK_MAGIC_SWAP_ALT_GUI",
    label: "Swap Alt\u21c4GUI",
    aliases: ["AG_SWAP"],
    group: "magic",
  },
  0x7015: {
    key: "QK_MAGIC_UNSWAP_ALT_GUI",
    label: "Unswap Alt\u21c4GUI",
    aliases: ["AG_NORM"],
    group: "magic",
  },
  0x7016: {
    key: "QK_MAGIC_TOGGLE_ALT_GUI",
    label: "Toggle Alt\u21c4GUI",
    aliases: ["AG_TOGG"],
    group: "magic",
  },
  0x7017: {
    key: "QK_MAGIC_SWAP_LCTL_LGUI",
    label: "Swap LCtl\u21c4LGUI",
    aliases: ["CG_LSWP"],
    group: "magic",
  },
  0x7018: {
    key: "QK_MAGIC_UNSWAP_LCTL_LGUI",
    label: "Unswap LCtl\u21c4LGUI",
    aliases: ["CG_LNRM"],
    group: "magic",
  },
  0x7019: {
    key: "QK_MAGIC_SWAP_RCTL_RGUI",
    label: "Swap RCtl\u21c4RGUI",
    aliases: ["CG_RSWP"],
    group: "magic",
  },
  0x701a: {
    key: "QK_MAGIC_UNSWAP_RCTL_RGUI",
    label: "Unswap RCtl\u21c4RGUI",
    aliases: ["CG_RNRM"],
    group: "magic",
  },
  0x701b: {
    key: "QK_MAGIC_SWAP_CTL_GUI",
    label: "Swap Ctl\u21c4GUI",
    aliases: ["CG_SWAP"],
    group: "magic",
  },
  0x701c: {
    key: "QK_MAGIC_UNSWAP_CTL_GUI",
    label: "Unswap Ctl\u21c4GUI",
    aliases: ["CG_NORM"],
    group: "magic",
  },
  0x701d: {
    key: "QK_MAGIC_TOGGLE_CTL_GUI",
    label: "Toggle Ctl\u21c4GUI",
    aliases: ["CG_TOGG"],
    group: "magic",
  },
  0x701e: {
    key: "QK_MAGIC_EE_HANDS_LEFT",
    label: "EE Hands Left",
    aliases: ["EH_LEFT"],
    group: "magic",
  },
  0x701f: {
    key: "QK_MAGIC_EE_HANDS_RIGHT",
    label: "EE Hands Right",
    aliases: ["EH_RGHT"],
    group: "magic",
  },
  0x7020: {
    key: "QK_MAGIC_SWAP_ESCAPE_CAPS_LOCK",
    label: "Swap Esc\u21c4Caps",
    aliases: ["EC_SWAP"],
    group: "magic",
  },
  0x7021: {
    key: "QK_MAGIC_UNSWAP_ESCAPE_CAPS_LOCK",
    label: "Unswap Esc\u21c4Caps",
    aliases: ["EC_NORM"],
    group: "magic",
  },
  0x7022: {
    key: "QK_MAGIC_TOGGLE_ESCAPE_CAPS_LOCK",
    label: "Toggle Esc\u21c4Caps",
    aliases: ["EC_TOGG"],
    group: "magic",
  },
  0x7100: { key: "QK_MIDI_ON", label: "MIDI On", aliases: ["MI_ON"], group: "midi" },
  0x7101: { key: "QK_MIDI_OFF", label: "MIDI Off", aliases: ["MI_OFF"], group: "midi" },
  0x7102: { key: "QK_MIDI_TOGGLE", label: "Toggle MIDI", aliases: ["MI_TOGG"], group: "midi" },
  0x7103: { key: "QK_MIDI_NOTE_C_0", label: "C\u2080", aliases: ["MI_C"], group: "midi" },
  0x7104: {
    key: "QK_MIDI_NOTE_C_SHARP_0",
    label: "C\u266f\u2080",
    aliases: ["MI_Cs", "MI_Db"],
    group: "midi",
  },
  0x7105: { key: "QK_MIDI_NOTE_D_0", label: "D\u2080", aliases: ["MI_D"], group: "midi" },
  0x7106: {
    key: "QK_MIDI_NOTE_D_SHARP_0",
    label: "D\u266f\u2080",
    aliases: ["MI_Ds", "MI_Eb"],
    group: "midi",
  },
  0x7107: { key: "QK_MIDI_NOTE_E_0", label: "E\u2080", aliases: ["MI_E"], group: "midi" },
  0x7108: { key: "QK_MIDI_NOTE_F_0", label: "F\u2080", aliases: ["MI_F"], group: "midi" },
  0x7109: {
    key: "QK_MIDI_NOTE_F_SHARP_0",
    label: "F\u266f\u2080",
    aliases: ["MI_Fs", "MI_Gb"],
    group: "midi",
  },
  0x710a: { key: "QK_MIDI_NOTE_G_0", label: "G\u2080", aliases: ["MI_G"], group: "midi" },
  0x710b: {
    key: "QK_MIDI_NOTE_G_SHARP_0",
    label: "G\u266f\u2080",
    aliases: ["MI_Ab", "MI_Gs"],
    group: "midi",
  },
  0x710c: { key: "QK_MIDI_NOTE_A_0", label: "A\u2080", aliases: ["MI_A"], group: "midi" },
  0x710d: {
    key: "QK_MIDI_NOTE_A_SHARP_0",
    label: "A\u266f\u2080",
    aliases: ["MI_As", "MI_Bb"],
    group: "midi",
  },
  0x710e: { key: "QK_MIDI_NOTE_B_0", label: "B\u2080", aliases: ["MI_B"], group: "midi" },
  0x710f: { key: "QK_MIDI_NOTE_C_1", label: "C\u2081", aliases: ["MI_C1"], group: "midi" },
  0x7110: {
    key: "QK_MIDI_NOTE_C_SHARP_1",
    label: "C\u266f\u2081",
    aliases: ["MI_Cs1", "MI_Db1"],
    group: "midi",
  },
  0x7111: { key: "QK_MIDI_NOTE_D_1", label: "D\u2081", aliases: ["MI_D1"], group: "midi" },
  0x7112: {
    key: "QK_MIDI_NOTE_D_SHARP_1",
    label: "D\u266f\u2081",
    aliases: ["MI_Ds1", "MI_Eb1"],
    group: "midi",
  },
  0x7113: { key: "QK_MIDI_NOTE_E_1", label: "E\u2081", aliases: ["MI_E1"], group: "midi" },
  0x7114: { key: "QK_MIDI_NOTE_F_1", label: "F\u2081", aliases: ["MI_F1"], group: "midi" },
  0x7115: {
    key: "QK_MIDI_NOTE_F_SHARP_1",
    label: "F\u266f\u2081",
    aliases: ["MI_Fs1", "MI_Gb1"],
    group: "midi",
  },
  0x7116: { key: "QK_MIDI_NOTE_G_1", label: "G\u2081", aliases: ["MI_G1"], group: "midi" },
  0x7117: {
    key: "QK_MIDI_NOTE_G_SHARP_1",
    label: "G\u266f\u2081",
    aliases: ["MI_Ab1", "MI_Gs1"],
    group: "midi",
  },
  0x7118: { key: "QK_MIDI_NOTE_A_1", label: "A\u2081", aliases: ["MI_A1"], group: "midi" },
  0x7119: {
    key: "QK_MIDI_NOTE_A_SHARP_1",
    label: "A\u266f\u2081",
    aliases: ["MI_As1", "MI_Bb1"],
    group: "midi",
  },
  0x711a: { key: "QK_MIDI_NOTE_B_1", label: "B\u2081", aliases: ["MI_B1"], group: "midi" },
  0x711b: { key: "QK_MIDI_NOTE_C_2", label: "C\u2082", aliases: ["MI_C2"], group: "midi" },
  0x711c: {
    key: "QK_MIDI_NOTE_C_SHARP_2",
    label: "C\u266f\u2082",
    aliases: ["MI_Cs2", "MI_Db2"],
    group: "midi",
  },
  0x711d: { key: "QK_MIDI_NOTE_D_2", label: "D\u2082", aliases: ["MI_D2"], group: "midi" },
  0x711e: {
    key: "QK_MIDI_NOTE_D_SHARP_2",
    label: "D\u266f\u2082",
    aliases: ["MI_Ds2", "MI_Eb2"],
    group: "midi",
  },
  0x711f: { key: "QK_MIDI_NOTE_E_2", label: "E\u2082", aliases: ["MI_E2"], group: "midi" },
  0x7120: { key: "QK_MIDI_NOTE_F_2", label: "F\u2082", aliases: ["MI_F2"], group: "midi" },
  0x7121: {
    key: "QK_MIDI_NOTE_F_SHARP_2",
    label: "F\u266f\u2082",
    aliases: ["MI_Fs2", "MI_Gb2"],
    group: "midi",
  },
  0x7122: { key: "QK_MIDI_NOTE_G_2", label: "G\u2082", aliases: ["MI_G2"], group: "midi" },
  0x7123: {
    key: "QK_MIDI_NOTE_G_SHARP_2",
    label: "G\u266f\u2082",
    aliases: ["MI_Ab2", "MI_Gs2"],
    group: "midi",
  },
  0x7124: { key: "QK_MIDI_NOTE_A_2", label: "A\u2082", aliases: ["MI_A2"], group: "midi" },
  0x7125: {
    key: "QK_MIDI_NOTE_A_SHARP_2",
    label: "A\u266f\u2082",
    aliases: ["MI_As2", "MI_Bb2"],
    group: "midi",
  },
  0x7126: { key: "QK_MIDI_NOTE_B_2", label: "B\u2082", aliases: ["MI_B2"], group: "midi" },
  0x7127: { key: "QK_MIDI_NOTE_C_3", label: "C\u2083", aliases: ["MI_C3"], group: "midi" },
  0x7128: {
    key: "QK_MIDI_NOTE_C_SHARP_3",
    label: "C\u266f\u2083",
    aliases: ["MI_Cs3", "MI_Db3"],
    group: "midi",
  },
  0x7129: { key: "QK_MIDI_NOTE_D_3", label: "D\u2083", aliases: ["MI_D3"], group: "midi" },
  0x712a: {
    key: "QK_MIDI_NOTE_D_SHARP_3",
    label: "D\u266f\u2083",
    aliases: ["MI_Ds3", "MI_Eb3"],
    group: "midi",
  },
  0x712b: { key: "QK_MIDI_NOTE_E_3", label: "E\u2083", aliases: ["MI_E3"], group: "midi" },
  0x712c: { key: "QK_MIDI_NOTE_F_3", label: "F\u2083", aliases: ["MI_F3"], group: "midi" },
  0x712d: {
    key: "QK_MIDI_NOTE_F_SHARP_3",
    label: "F\u266f\u2083",
    aliases: ["MI_Fs3", "MI_Gb3"],
    group: "midi",
  },
  0x712e: { key: "QK_MIDI_NOTE_G_3", label: "G\u2083", aliases: ["MI_G3"], group: "midi" },
  0x712f: {
    key: "QK_MIDI_NOTE_G_SHARP_3",
    label: "G\u266f\u2083",
    aliases: ["MI_Ab3", "MI_Gs3"],
    group: "midi",
  },
  0x7130: { key: "QK_MIDI_NOTE_A_3", label: "A\u2083", aliases: ["MI_A3"], group: "midi" },
  0x7131: {
    key: "QK_MIDI_NOTE_A_SHARP_3",
    label: "A\u266f\u2083",
    aliases: ["MI_As3", "MI_Bb3"],
    group: "midi",
  },
  0x7132: { key: "QK_MIDI_NOTE_B_3", label: "B\u2083", aliases: ["MI_B3"], group: "midi" },
  0x7133: { key: "QK_MIDI_NOTE_C_4", label: "C\u2084", aliases: ["MI_C4"], group: "midi" },
  0x7134: {
    key: "QK_MIDI_NOTE_C_SHARP_4",
    label: "C\u266f\u2084",
    aliases: ["MI_Cs4", "MI_Db4"],
    group: "midi",
  },
  0x7135: { key: "QK_MIDI_NOTE_D_4", label: "D\u2084", aliases: ["MI_D4"], group: "midi" },
  0x7136: {
    key: "QK_MIDI_NOTE_D_SHARP_4",
    label: "D\u266f\u2084",
    aliases: ["MI_Ds4", "MI_Eb4"],
    group: "midi",
  },
  0x7137: { key: "QK_MIDI_NOTE_E_4", label: "E\u2084", aliases: ["MI_E4"], group: "midi" },
  0x7138: { key: "QK_MIDI_NOTE_F_4", label: "F\u2084", aliases: ["MI_F4"], group: "midi" },
  0x7139: {
    key: "QK_MIDI_NOTE_F_SHARP_4",
    label: "F\u266f\u2084",
    aliases: ["MI_Fs4", "MI_Gb4"],
    group: "midi",
  },
  0x713a: { key: "QK_MIDI_NOTE_G_4", label: "G\u2084", aliases: ["MI_G4"], group: "midi" },
  0x713b: {
    key: "QK_MIDI_NOTE_G_SHARP_4",
    label: "G\u266f\u2084",
    aliases: ["MI_Ab4", "MI_Gs4"],
    group: "midi",
  },
  0x713c: { key: "QK_MIDI_NOTE_A_4", label: "A\u2084", aliases: ["MI_A4"], group: "midi" },
  0x713d: {
    key: "QK_MIDI_NOTE_A_SHARP_4",
    label: "A\u266f\u2084",
    aliases: ["MI_As4", "MI_Bb4"],
    group: "midi",
  },
  0x713e: { key: "QK_MIDI_NOTE_B_4", label: "B\u2084", aliases: ["MI_B4"], group: "midi" },
  0x713f: { key: "QK_MIDI_NOTE_C_5", label: "C\u2085", aliases: ["MI_C5"], group: "midi" },
  0x7140: {
    key: "QK_MIDI_NOTE_C_SHARP_5",
    label: "C\u266f\u2085",
    aliases: ["MI_Cs5", "MI_Db5"],
    group: "midi",
  },
  0x7141: { key: "QK_MIDI_NOTE_D_5", label: "D\u2085", aliases: ["MI_D5"], group: "midi" },
  0x7142: {
    key: "QK_MIDI_NOTE_D_SHARP_5",
    label: "D\u266f\u2085",
    aliases: ["MI_Ds5", "MI_Eb5"],
    group: "midi",
  },
  0x7143: { key: "QK_MIDI_NOTE_E_5", label: "E\u2085", aliases: ["MI_E5"], group: "midi" },
  0x7144: { key: "QK_MIDI_NOTE_F_5", label: "F\u2085", aliases: ["MI_F5"], group: "midi" },
  0x7145: {
    key: "QK_MIDI_NOTE_F_SHARP_5",
    label: "F\u266f\u2085",
    aliases: ["MI_Fs5", "MI_Gb5"],
    group: "midi",
  },
  0x7146: { key: "QK_MIDI_NOTE_G_5", label: "G\u2085", aliases: ["MI_G5"], group: "midi" },
  0x7147: {
    key: "QK_MIDI_NOTE_G_SHARP_5",
    label: "G\u266f\u2085",
    aliases: ["MI_Ab5", "MI_Gs5"],
    group: "midi",
  },
  0x7148: { key: "QK_MIDI_NOTE_A_5", label: "A\u2085", aliases: ["MI_A5"], group: "midi" },
  0x7149: {
    key: "QK_MIDI_NOTE_A_SHARP_5",
    label: "A\u266f\u2085",
    aliases: ["MI_As5", "MI_Bb5"],
    group: "midi",
  },
  0x714a: { key: "QK_MIDI_NOTE_B_5", label: "B\u2085", aliases: ["MI_B5"], group: "midi" },
  0x714b: { key: "QK_MIDI_OCTAVE_N2", label: "Octave -2", aliases: ["MI_OCN2"], group: "midi" },
  0x714c: { key: "QK_MIDI_OCTAVE_N1", label: "Octave -1", aliases: ["MI_OCN1"], group: "midi" },
  0x714d: { key: "QK_MIDI_OCTAVE_0", label: "Octave 0", aliases: ["MI_OC0"], group: "midi" },
  0x714e: { key: "QK_MIDI_OCTAVE_1", label: "Octave 1", aliases: ["MI_OC1"], group: "midi" },
  0x714f: { key: "QK_MIDI_OCTAVE_2", label: "Octave 2", aliases: ["MI_OC2"], group: "midi" },
  0x7150: { key: "QK_MIDI_OCTAVE_3", label: "Octave 3", aliases: ["MI_OC3"], group: "midi" },
  0x7151: { key: "QK_MIDI_OCTAVE_4", label: "Octave 4", aliases: ["MI_OC4"], group: "midi" },
  0x7152: { key: "QK_MIDI_OCTAVE_5", label: "Octave 5", aliases: ["MI_OC5"], group: "midi" },
  0x7153: { key: "QK_MIDI_OCTAVE_6", label: "Octave 6", aliases: ["MI_OC6"], group: "midi" },
  0x7154: { key: "QK_MIDI_OCTAVE_7", label: "Octave 7", aliases: ["MI_OC7"], group: "midi" },
  0x7155: { key: "QK_MIDI_OCTAVE_DOWN", label: "Octave Down", aliases: ["MI_OCTD"], group: "midi" },
  0x7156: { key: "QK_MIDI_OCTAVE_UP", label: "Octave Up", aliases: ["MI_OCTU"], group: "midi" },
  0x7157: {
    key: "QK_MIDI_TRANSPOSE_N6",
    label: "Transpose -6",
    aliases: ["MI_TRN6"],
    group: "midi",
  },
  0x7158: {
    key: "QK_MIDI_TRANSPOSE_N5",
    label: "Transpose -5",
    aliases: ["MI_TRN5"],
    group: "midi",
  },
  0x7159: {
    key: "QK_MIDI_TRANSPOSE_N4",
    label: "Transpose -4",
    aliases: ["MI_TRN4"],
    group: "midi",
  },
  0x715a: {
    key: "QK_MIDI_TRANSPOSE_N3",
    label: "Transpose -3",
    aliases: ["MI_TRN3"],
    group: "midi",
  },
  0x715b: {
    key: "QK_MIDI_TRANSPOSE_N2",
    label: "Transpose -2",
    aliases: ["MI_TRN2"],
    group: "midi",
  },
  0x715c: {
    key: "QK_MIDI_TRANSPOSE_N1",
    label: "Transpose -1",
    aliases: ["MI_TRN1"],
    group: "midi",
  },
  0x715d: { key: "QK_MIDI_TRANSPOSE_0", label: "Transpose 0", aliases: ["MI_TR0"], group: "midi" },
  0x715e: { key: "QK_MIDI_TRANSPOSE_1", label: "Transpose +1", aliases: ["MI_TR1"], group: "midi" },
  0x715f: { key: "QK_MIDI_TRANSPOSE_2", label: "Transpose +2", aliases: ["MI_TR2"], group: "midi" },
  0x7160: { key: "QK_MIDI_TRANSPOSE_3", label: "Transpose +3", aliases: ["MI_TR3"], group: "midi" },
  0x7161: { key: "QK_MIDI_TRANSPOSE_4", label: "Transpose +4", aliases: ["MI_TR4"], group: "midi" },
  0x7162: { key: "QK_MIDI_TRANSPOSE_5", label: "Transpose +5", aliases: ["MI_TR5"], group: "midi" },
  0x7163: { key: "QK_MIDI_TRANSPOSE_6", label: "Transpose +6", aliases: ["MI_TR6"], group: "midi" },
  0x7164: {
    key: "QK_MIDI_TRANSPOSE_DOWN",
    label: "Transpose Down",
    aliases: ["MI_TRSD"],
    group: "midi",
  },
  0x7165: {
    key: "QK_MIDI_TRANSPOSE_UP",
    label: "Transpose Up",
    aliases: ["MI_TRSU"],
    group: "midi",
  },
  0x7166: { key: "QK_MIDI_VELOCITY_0", label: "Velocity 0", aliases: ["MI_VL0"], group: "midi" },
  0x7167: { key: "QK_MIDI_VELOCITY_1", label: "Velocity 1", aliases: ["MI_VL1"], group: "midi" },
  0x7168: { key: "QK_MIDI_VELOCITY_2", label: "Velocity 2", aliases: ["MI_VL2"], group: "midi" },
  0x7169: { key: "QK_MIDI_VELOCITY_3", label: "Velocity 3", aliases: ["MI_VL3"], group: "midi" },
  0x716a: { key: "QK_MIDI_VELOCITY_4", label: "Velocity 4", aliases: ["MI_VL4"], group: "midi" },
  0x716b: { key: "QK_MIDI_VELOCITY_5", label: "Velocity 5", aliases: ["MI_VL5"], group: "midi" },
  0x716c: { key: "QK_MIDI_VELOCITY_6", label: "Velocity 6", aliases: ["MI_VL6"], group: "midi" },
  0x716d: { key: "QK_MIDI_VELOCITY_7", label: "Velocity 7", aliases: ["MI_VL7"], group: "midi" },
  0x716e: { key: "QK_MIDI_VELOCITY_8", label: "Velocity 8", aliases: ["MI_VL8"], group: "midi" },
  0x716f: { key: "QK_MIDI_VELOCITY_9", label: "Velocity 9", aliases: ["MI_VL9"], group: "midi" },
  0x7170: { key: "QK_MIDI_VELOCITY_10", label: "Velocity 10", aliases: ["MI_VL10"], group: "midi" },
  0x7171: {
    key: "QK_MIDI_VELOCITY_DOWN",
    label: "Velocity Down",
    aliases: ["MI_VELD"],
    group: "midi",
  },
  0x7172: { key: "QK_MIDI_VELOCITY_UP", label: "Velocity Up", aliases: ["MI_VELU"], group: "midi" },
  0x7173: { key: "QK_MIDI_CHANNEL_1", label: "Channel 1", aliases: ["MI_CH1"], group: "midi" },
  0x7174: { key: "QK_MIDI_CHANNEL_2", label: "Channel 2", aliases: ["MI_CH2"], group: "midi" },
  0x7175: { key: "QK_MIDI_CHANNEL_3", label: "Channel 3", aliases: ["MI_CH3"], group: "midi" },
  0x7176: { key: "QK_MIDI_CHANNEL_4", label: "Channel 4", aliases: ["MI_CH4"], group: "midi" },
  0x7177: { key: "QK_MIDI_CHANNEL_5", label: "Channel 5", aliases: ["MI_CH5"], group: "midi" },
  0x7178: { key: "QK_MIDI_CHANNEL_6", label: "Channel 6", aliases: ["MI_CH6"], group: "midi" },
  0x7179: { key: "QK_MIDI_CHANNEL_7", label: "Channel 7", aliases: ["MI_CH7"], group: "midi" },
  0x717a: { key: "QK_MIDI_CHANNEL_8", label: "Channel 8", aliases: ["MI_CH8"], group: "midi" },
  0x717b: { key: "QK_MIDI_CHANNEL_9", label: "Channel 9", aliases: ["MI_CH9"], group: "midi" },
  0x717c: { key: "QK_MIDI_CHANNEL_10", label: "Channel 10", aliases: ["MI_CH10"], group: "midi" },
  0x717d: { key: "QK_MIDI_CHANNEL_11", label: "Channel 11", aliases: ["MI_CH11"], group: "midi" },
  0x717e: { key: "QK_MIDI_CHANNEL_12", label: "Channel 12", aliases: ["MI_CH12"], group: "midi" },
  0x717f: { key: "QK_MIDI_CHANNEL_13", label: "Channel 13", aliases: ["MI_CH13"], group: "midi" },
  0x7180: { key: "QK_MIDI_CHANNEL_14", label: "Channel 14", aliases: ["MI_CH14"], group: "midi" },
  0x7181: { key: "QK_MIDI_CHANNEL_15", label: "Channel 15", aliases: ["MI_CH15"], group: "midi" },
  0x7182: { key: "QK_MIDI_CHANNEL_16", label: "Channel 16", aliases: ["MI_CH16"], group: "midi" },
  0x7183: {
    key: "QK_MIDI_CHANNEL_DOWN",
    label: "Channel Down",
    aliases: ["MI_CHND"],
    group: "midi",
  },
  0x7184: { key: "QK_MIDI_CHANNEL_UP", label: "Channel Up", aliases: ["MI_CHNU"], group: "midi" },
  0x7185: {
    key: "QK_MIDI_ALL_NOTES_OFF",
    label: "All Notes Off",
    aliases: ["MI_AOFF"],
    group: "midi",
  },
  0x7186: { key: "QK_MIDI_SUSTAIN", label: "Sustain", aliases: ["MI_SUST"], group: "midi" },
  0x7187: { key: "QK_MIDI_PORTAMENTO", label: "Portamento", aliases: ["MI_PORT"], group: "midi" },
  0x7188: { key: "QK_MIDI_SOSTENUTO", label: "Sostenuto", aliases: ["MI_SOST"], group: "midi" },
  0x7189: { key: "QK_MIDI_SOFT", label: "Soft Pedal", aliases: ["MI_SOFT"], group: "midi" },
  0x718a: { key: "QK_MIDI_LEGATO", label: "Legato", aliases: ["MI_LEG"], group: "midi" },
  0x718b: { key: "QK_MIDI_MODULATION", label: "Modulation", aliases: ["MI_MOD"], group: "midi" },
  0x718c: {
    key: "QK_MIDI_MODULATION_SPEED_DOWN",
    label: "Modulation Speed Down",
    aliases: ["MI_MODD"],
    group: "midi",
  },
  0x718d: {
    key: "QK_MIDI_MODULATION_SPEED_UP",
    label: "Modulation Speed Up",
    aliases: ["MI_MODU"],
    group: "midi",
  },
  0x718e: {
    key: "QK_MIDI_PITCH_BEND_DOWN",
    label: "Pitch Bend Down",
    aliases: ["MI_BNDD"],
    group: "midi",
  },
  0x718f: {
    key: "QK_MIDI_PITCH_BEND_UP",
    label: "Pitch Bend Up",
    aliases: ["MI_BNDU"],
    group: "midi",
  },
  0x7200: { key: "QK_SEQUENCER_ON", label: "Sequencer On", aliases: ["SQ_ON"], group: "sequencer" },
  0x7201: {
    key: "QK_SEQUENCER_OFF",
    label: "Sequencer Off",
    aliases: ["SQ_OFF"],
    group: "sequencer",
  },
  0x7202: {
    key: "QK_SEQUENCER_TOGGLE",
    label: "Toggle Sequencer",
    aliases: ["SQ_TOGG"],
    group: "sequencer",
  },
  0x7203: {
    key: "QK_SEQUENCER_TEMPO_DOWN",
    label: "Tempo Down",
    aliases: ["SQ_TMPD"],
    group: "sequencer",
  },
  0x7204: {
    key: "QK_SEQUENCER_TEMPO_UP",
    label: "Tempo Up",
    aliases: ["SQ_TMPU"],
    group: "sequencer",
  },
  0x7205: {
    key: "QK_SEQUENCER_RESOLUTION_DOWN",
    label: "Resolution Down",
    aliases: ["SQ_RESD"],
    group: "sequencer",
  },
  0x7206: {
    key: "QK_SEQUENCER_RESOLUTION_UP",
    label: "Resolution Up",
    aliases: ["SQ_RESU"],
    group: "sequencer",
  },
  0x7207: {
    key: "QK_SEQUENCER_STEPS_ALL",
    label: "All Steps",
    aliases: ["SQ_SALL"],
    group: "sequencer",
  },
  0x7208: {
    key: "QK_SEQUENCER_STEPS_CLEAR",
    label: "Clear Steps",
    aliases: ["SQ_SCLR"],
    group: "sequencer",
  },
  0x7400: { key: "QK_JOYSTICK_BUTTON_0", label: "Button 0", aliases: ["JS_0"], group: "joystick" },
  0x7401: { key: "QK_JOYSTICK_BUTTON_1", label: "Button 1", aliases: ["JS_1"], group: "joystick" },
  0x7402: { key: "QK_JOYSTICK_BUTTON_2", label: "Button 2", aliases: ["JS_2"], group: "joystick" },
  0x7403: { key: "QK_JOYSTICK_BUTTON_3", label: "Button 3", aliases: ["JS_3"], group: "joystick" },
  0x7404: { key: "QK_JOYSTICK_BUTTON_4", label: "Button 4", aliases: ["JS_4"], group: "joystick" },
  0x7405: { key: "QK_JOYSTICK_BUTTON_5", label: "Button 5", aliases: ["JS_5"], group: "joystick" },
  0x7406: { key: "QK_JOYSTICK_BUTTON_6", label: "Button 6", aliases: ["JS_6"], group: "joystick" },
  0x7407: { key: "QK_JOYSTICK_BUTTON_7", label: "Button 7", aliases: ["JS_7"], group: "joystick" },
  0x7408: { key: "QK_JOYSTICK_BUTTON_8", label: "Button 8", aliases: ["JS_8"], group: "joystick" },
  0x7409: { key: "QK_JOYSTICK_BUTTON_9", label: "Button 9", aliases: ["JS_9"], group: "joystick" },
  0x740a: {
    key: "QK_JOYSTICK_BUTTON_10",
    label: "Button 10",
    aliases: ["JS_10"],
    group: "joystick",
  },
  0x740b: {
    key: "QK_JOYSTICK_BUTTON_11",
    label: "Button 11",
    aliases: ["JS_11"],
    group: "joystick",
  },
  0x740c: {
    key: "QK_JOYSTICK_BUTTON_12",
    label: "Button 12",
    aliases: ["JS_12"],
    group: "joystick",
  },
  0x740d: {
    key: "QK_JOYSTICK_BUTTON_13",
    label: "Button 13",
    aliases: ["JS_13"],
    group: "joystick",
  },
  0x740e: {
    key: "QK_JOYSTICK_BUTTON_14",
    label: "Button 14",
    aliases: ["JS_14"],
    group: "joystick",
  },
  0x740f: {
    key: "QK_JOYSTICK_BUTTON_15",
    label: "Button 15",
    aliases: ["JS_15"],
    group: "joystick",
  },
  0x7410: {
    key: "QK_JOYSTICK_BUTTON_16",
    label: "Button 16",
    aliases: ["JS_16"],
    group: "joystick",
  },
  0x7411: {
    key: "QK_JOYSTICK_BUTTON_17",
    label: "Button 17",
    aliases: ["JS_17"],
    group: "joystick",
  },
  0x7412: {
    key: "QK_JOYSTICK_BUTTON_18",
    label: "Button 18",
    aliases: ["JS_18"],
    group: "joystick",
  },
  0x7413: {
    key: "QK_JOYSTICK_BUTTON_19",
    label: "Button 19",
    aliases: ["JS_19"],
    group: "joystick",
  },
  0x7414: {
    key: "QK_JOYSTICK_BUTTON_20",
    label: "Button 20",
    aliases: ["JS_20"],
    group: "joystick",
  },
  0x7415: {
    key: "QK_JOYSTICK_BUTTON_21",
    label: "Button 21",
    aliases: ["JS_21"],
    group: "joystick",
  },
  0x7416: {
    key: "QK_JOYSTICK_BUTTON_22",
    label: "Button 22",
    aliases: ["JS_22"],
    group: "joystick",
  },
  0x7417: {
    key: "QK_JOYSTICK_BUTTON_23",
    label: "Button 23",
    aliases: ["JS_23"],
    group: "joystick",
  },
  0x7418: {
    key: "QK_JOYSTICK_BUTTON_24",
    label: "Button 24",
    aliases: ["JS_24"],
    group: "joystick",
  },
  0x7419: {
    key: "QK_JOYSTICK_BUTTON_25",
    label: "Button 25",
    aliases: ["JS_25"],
    group: "joystick",
  },
  0x741a: {
    key: "QK_JOYSTICK_BUTTON_26",
    label: "Button 26",
    aliases: ["JS_26"],
    group: "joystick",
  },
  0x741b: {
    key: "QK_JOYSTICK_BUTTON_27",
    label: "Button 27",
    aliases: ["JS_27"],
    group: "joystick",
  },
  0x741c: {
    key: "QK_JOYSTICK_BUTTON_28",
    label: "Button 28",
    aliases: ["JS_28"],
    group: "joystick",
  },
  0x741d: {
    key: "QK_JOYSTICK_BUTTON_29",
    label: "Button 29",
    aliases: ["JS_29"],
    group: "joystick",
  },
  0x741e: {
    key: "QK_JOYSTICK_BUTTON_30",
    label: "Button 30",
    aliases: ["JS_30"],
    group: "joystick",
  },
  0x741f: {
    key: "QK_JOYSTICK_BUTTON_31",
    label: "Button 31",
    aliases: ["JS_31"],
    group: "joystick",
  },
  0x7440: {
    key: "QK_PROGRAMMABLE_BUTTON_1",
    label: "Button 1",
    aliases: ["PB_1"],
    group: "programmable_button",
  },
  0x7441: {
    key: "QK_PROGRAMMABLE_BUTTON_2",
    label: "Button 2",
    aliases: ["PB_2"],
    group: "programmable_button",
  },
  0x7442: {
    key: "QK_PROGRAMMABLE_BUTTON_3",
    label: "Button 3",
    aliases: ["PB_3"],
    group: "programmable_button",
  },
  0x7443: {
    key: "QK_PROGRAMMABLE_BUTTON_4",
    label: "Button 4",
    aliases: ["PB_4"],
    group: "programmable_button",
  },
  0x7444: {
    key: "QK_PROGRAMMABLE_BUTTON_5",
    label: "Button 5",
    aliases: ["PB_5"],
    group: "programmable_button",
  },
  0x7445: {
    key: "QK_PROGRAMMABLE_BUTTON_6",
    label: "Button 6",
    aliases: ["PB_6"],
    group: "programmable_button",
  },
  0x7446: {
    key: "QK_PROGRAMMABLE_BUTTON_7",
    label: "Button 7",
    aliases: ["PB_7"],
    group: "programmable_button",
  },
  0x7447: {
    key: "QK_PROGRAMMABLE_BUTTON_8",
    label: "Button 8",
    aliases: ["PB_8"],
    group: "programmable_button",
  },
  0x7448: {
    key: "QK_PROGRAMMABLE_BUTTON_9",
    label: "Button 9",
    aliases: ["PB_9"],
    group: "programmable_button",
  },
  0x7449: {
    key: "QK_PROGRAMMABLE_BUTTON_10",
    label: "Button 10",
    aliases: ["PB_10"],
    group: "programmable_button",
  },
  0x744a: {
    key: "QK_PROGRAMMABLE_BUTTON_11",
    label: "Button 11",
    aliases: ["PB_11"],
    group: "programmable_button",
  },
  0x744b: {
    key: "QK_PROGRAMMABLE_BUTTON_12",
    label: "Button 12",
    aliases: ["PB_12"],
    group: "programmable_button",
  },
  0x744c: {
    key: "QK_PROGRAMMABLE_BUTTON_13",
    label: "Button 13",
    aliases: ["PB_13"],
    group: "programmable_button",
  },
  0x744d: {
    key: "QK_PROGRAMMABLE_BUTTON_14",
    label: "Button 14",
    aliases: ["PB_14"],
    group: "programmable_button",
  },
  0x744e: {
    key: "QK_PROGRAMMABLE_BUTTON_15",
    label: "Button 15",
    aliases: ["PB_15"],
    group: "programmable_button",
  },
  0x744f: {
    key: "QK_PROGRAMMABLE_BUTTON_16",
    label: "Button 16",
    aliases: ["PB_16"],
    group: "programmable_button",
  },
  0x7450: {
    key: "QK_PROGRAMMABLE_BUTTON_17",
    label: "Button 17",
    aliases: ["PB_17"],
    group: "programmable_button",
  },
  0x7451: {
    key: "QK_PROGRAMMABLE_BUTTON_18",
    label: "Button 18",
    aliases: ["PB_18"],
    group: "programmable_button",
  },
  0x7452: {
    key: "QK_PROGRAMMABLE_BUTTON_19",
    label: "Button 19",
    aliases: ["PB_19"],
    group: "programmable_button",
  },
  0x7453: {
    key: "QK_PROGRAMMABLE_BUTTON_20",
    label: "Button 20",
    aliases: ["PB_20"],
    group: "programmable_button",
  },
  0x7454: {
    key: "QK_PROGRAMMABLE_BUTTON_21",
    label: "Button 21",
    aliases: ["PB_21"],
    group: "programmable_button",
  },
  0x7455: {
    key: "QK_PROGRAMMABLE_BUTTON_22",
    label: "Button 22",
    aliases: ["PB_22"],
    group: "programmable_button",
  },
  0x7456: {
    key: "QK_PROGRAMMABLE_BUTTON_23",
    label: "Button 23",
    aliases: ["PB_23"],
    group: "programmable_button",
  },
  0x7457: {
    key: "QK_PROGRAMMABLE_BUTTON_24",
    label: "Button 24",
    aliases: ["PB_24"],
    group: "programmable_button",
  },
  0x7458: {
    key: "QK_PROGRAMMABLE_BUTTON_25",
    label: "Button 25",
    aliases: ["PB_25"],
    group: "programmable_button",
  },
  0x7459: {
    key: "QK_PROGRAMMABLE_BUTTON_26",
    label: "Button 26",
    aliases: ["PB_26"],
    group: "programmable_button",
  },
  0x745a: {
    key: "QK_PROGRAMMABLE_BUTTON_27",
    label: "Button 27",
    aliases: ["PB_27"],
    group: "programmable_button",
  },
  0x745b: {
    key: "QK_PROGRAMMABLE_BUTTON_28",
    label: "Button 28",
    aliases: ["PB_28"],
    group: "programmable_button",
  },
  0x745c: {
    key: "QK_PROGRAMMABLE_BUTTON_29",
    label: "Button 29",
    aliases: ["PB_29"],
    group: "programmable_button",
  },
  0x745d: {
    key: "QK_PROGRAMMABLE_BUTTON_30",
    label: "Button 30",
    aliases: ["PB_30"],
    group: "programmable_button",
  },
  0x745e: {
    key: "QK_PROGRAMMABLE_BUTTON_31",
    label: "Button 31",
    aliases: ["PB_31"],
    group: "programmable_button",
  },
  0x745f: {
    key: "QK_PROGRAMMABLE_BUTTON_32",
    label: "Button 32",
    aliases: ["PB_32"],
    group: "programmable_button",
  },
  0x7480: { key: "QK_AUDIO_ON", label: "Audio On", aliases: ["AU_ON"], group: "audio" },
  0x7481: { key: "QK_AUDIO_OFF", label: "Audio Off", aliases: ["AU_OFF"], group: "audio" },
  0x7482: { key: "QK_AUDIO_TOGGLE", label: "Toggle Audio", aliases: ["AU_TOGG"], group: "audio" },
  0x748a: {
    key: "QK_AUDIO_CLICKY_TOGGLE",
    label: "Toggle Audio Clicky",
    aliases: ["CK_TOGG"],
    group: "audio",
  },
  0x748b: {
    key: "QK_AUDIO_CLICKY_ON",
    label: "Audio Clicky On",
    aliases: ["CK_ON"],
    group: "audio",
  },
  0x748c: {
    key: "QK_AUDIO_CLICKY_OFF",
    label: "Audio Clicky Off",
    aliases: ["CK_OFF"],
    group: "audio",
  },
  0x748d: {
    key: "QK_AUDIO_CLICKY_UP",
    label: "Audio Clicky Up",
    aliases: ["CK_UP"],
    group: "audio",
  },
  0x748e: {
    key: "QK_AUDIO_CLICKY_DOWN",
    label: "Audio Clicky Down",
    aliases: ["CK_DOWN"],
    group: "audio",
  },
  0x748f: {
    key: "QK_AUDIO_CLICKY_RESET",
    label: "Audio Clicky Reset",
    aliases: ["CK_RST"],
    group: "audio",
  },
  0x7490: { key: "QK_MUSIC_ON", label: "Music On", aliases: ["MU_ON"], group: "audio" },
  0x7491: { key: "QK_MUSIC_OFF", label: "Music Off", aliases: ["MU_OFF"], group: "audio" },
  0x7492: { key: "QK_MUSIC_TOGGLE", label: "Toggle Music", aliases: ["MU_TOGG"], group: "audio" },
  0x7493: { key: "QK_MUSIC_MODE_NEXT", label: "Music Next", aliases: ["MU_NEXT"], group: "audio" },
  0x7494: {
    key: "QK_AUDIO_VOICE_NEXT",
    label: "Audio Voice Next",
    aliases: ["AU_NEXT"],
    group: "audio",
  },
  0x7495: {
    key: "QK_AUDIO_VOICE_PREVIOUS",
    label: "Audio Voice Previous",
    aliases: ["AU_PREV"],
    group: "audio",
  },
  0x74f0: { key: "QK_STENO_BOLT", label: "Steno Bolt", aliases: [] },
  0x74f1: { key: "QK_STENO_GEMINI", label: "Steno Gemini", aliases: [] },
  0x74f2: { key: "QK_STENO_COMB", label: "Steno Comb", aliases: [] },
  0x74fc: { key: "QK_STENO_COMB_MAX", label: "Steno Comb Max", aliases: [] },
  0x7700: { key: "QK_MACRO_0", label: "Macro 0", aliases: ["MC_0"], group: "macro" },
  0x7701: { key: "QK_MACRO_1", label: "Macro 1", aliases: ["MC_1"], group: "macro" },
  0x7702: { key: "QK_MACRO_2", label: "Macro 2", aliases: ["MC_2"], group: "macro" },
  0x7703: { key: "QK_MACRO_3", label: "Macro 3", aliases: ["MC_3"], group: "macro" },
  0x7704: { key: "QK_MACRO_4", label: "Macro 4", aliases: ["MC_4"], group: "macro" },
  0x7705: { key: "QK_MACRO_5", label: "Macro 5", aliases: ["MC_5"], group: "macro" },
  0x7706: { key: "QK_MACRO_6", label: "Macro 6", aliases: ["MC_6"], group: "macro" },
  0x7707: { key: "QK_MACRO_7", label: "Macro 7", aliases: ["MC_7"], group: "macro" },
  0x7708: { key: "QK_MACRO_8", label: "Macro 8", aliases: ["MC_8"], group: "macro" },
  0x7709: { key: "QK_MACRO_9", label: "Macro 9", aliases: ["MC_9"], group: "macro" },
  0x770a: { key: "QK_MACRO_10", label: "Macro 10", aliases: ["MC_10"], group: "macro" },
  0x770b: { key: "QK_MACRO_11", label: "Macro 11", aliases: ["MC_11"], group: "macro" },
  0x770c: { key: "QK_MACRO_12", label: "Macro 12", aliases: ["MC_12"], group: "macro" },
  0x770d: { key: "QK_MACRO_13", label: "Macro 13", aliases: ["MC_13"], group: "macro" },
  0x770e: { key: "QK_MACRO_14", label: "Macro 14", aliases: ["MC_14"], group: "macro" },
  0x770f: { key: "QK_MACRO_15", label: "Macro 15", aliases: ["MC_15"], group: "macro" },
  0x7710: { key: "QK_MACRO_16", label: "Macro 16", aliases: ["MC_16"], group: "macro" },
  0x7711: { key: "QK_MACRO_17", label: "Macro 17", aliases: ["MC_17"], group: "macro" },
  0x7712: { key: "QK_MACRO_18", label: "Macro 18", aliases: ["MC_18"], group: "macro" },
  0x7713: { key: "QK_MACRO_19", label: "Macro 19", aliases: ["MC_19"], group: "macro" },
  0x7714: { key: "QK_MACRO_20", label: "Macro 20", aliases: ["MC_20"], group: "macro" },
  0x7715: { key: "QK_MACRO_21", label: "Macro 21", aliases: ["MC_21"], group: "macro" },
  0x7716: { key: "QK_MACRO_22", label: "Macro 22", aliases: ["MC_22"], group: "macro" },
  0x7717: { key: "QK_MACRO_23", label: "Macro 23", aliases: ["MC_23"], group: "macro" },
  0x7718: { key: "QK_MACRO_24", label: "Macro 24", aliases: ["MC_24"], group: "macro" },
  0x7719: { key: "QK_MACRO_25", label: "Macro 25", aliases: ["MC_25"], group: "macro" },
  0x771a: { key: "QK_MACRO_26", label: "Macro 26", aliases: ["MC_26"], group: "macro" },
  0x771b: { key: "QK_MACRO_27", label: "Macro 27", aliases: ["MC_27"], group: "macro" },
  0x771c: { key: "QK_MACRO_28", label: "Macro 28", aliases: ["MC_28"], group: "macro" },
  0x771d: { key: "QK_MACRO_29", label: "Macro 29", aliases: ["MC_29"], group: "macro" },
  0x771e: { key: "QK_MACRO_30", label: "Macro 30", aliases: ["MC_30"], group: "macro" },
  0x771f: { key: "QK_MACRO_31", label: "Macro 31", aliases: ["MC_31"], group: "macro" },
  0x7780: {
    key: "QK_OUTPUT_AUTO",
    label: "Output Auto",
    aliases: ["OU_AUTO"],
    group: "connection",
  },
  0x7781: {
    key: "QK_OUTPUT_NEXT",
    label: "Next Output",
    aliases: ["OU_NEXT"],
    group: "connection",
  },
  0x7782: {
    key: "QK_OUTPUT_PREV",
    label: "Previous Output",
    aliases: ["OU_PREV"],
    group: "connection",
  },
  0x7783: { key: "QK_OUTPUT_NONE", label: "None", aliases: ["OU_NONE"], group: "connection" },
  0x7784: { key: "QK_OUTPUT_USB", label: "USB", aliases: ["OU_USB"], group: "connection" },
  0x7785: { key: "QK_OUTPUT_2P4GHZ", label: "2.4GHz", aliases: ["OU_2P4G"], group: "connection" },
  0x7786: {
    key: "QK_OUTPUT_BLUETOOTH",
    label: "Bluetooth",
    aliases: ["OU_BT"],
    group: "connection",
  },
  0x7790: {
    key: "QK_BLUETOOTH_PROFILE_NEXT",
    label: "Bluetooth Profile Next",
    aliases: ["BT_NEXT"],
    group: "connection",
  },
  0x7791: {
    key: "QK_BLUETOOTH_PROFILE_PREV",
    label: "Bluetooth Profile Previous",
    aliases: ["BT_PREV"],
    group: "connection",
  },
  0x7792: {
    key: "QK_BLUETOOTH_UNPAIR",
    label: "Unpair",
    aliases: ["BT_UNPR"],
    group: "connection",
  },
  0x7793: {
    key: "QK_BLUETOOTH_PROFILE1",
    label: "Bluetooth Profile 1",
    aliases: ["BT_PRF1"],
    group: "connection",
  },
  0x7794: {
    key: "QK_BLUETOOTH_PROFILE2",
    label: "Bluetooth Profile 2",
    aliases: ["BT_PRF2"],
    group: "connection",
  },
  0x7795: {
    key: "QK_BLUETOOTH_PROFILE3",
    label: "Bluetooth Profile 3",
    aliases: ["BT_PRF3"],
    group: "connection",
  },
  0x7796: {
    key: "QK_BLUETOOTH_PROFILE4",
    label: "Bluetooth Profile 4",
    aliases: ["BT_PRF4"],
    group: "connection",
  },
  0x7797: {
    key: "QK_BLUETOOTH_PROFILE5",
    label: "Bluetooth Profile 5",
    aliases: ["BT_PRF5"],
    group: "connection",
  },
  0x7800: { key: "QK_BACKLIGHT_ON", label: "Backlight On", aliases: ["BL_ON"], group: "backlight" },
  0x7801: {
    key: "QK_BACKLIGHT_OFF",
    label: "Backlight Off",
    aliases: ["BL_OFF"],
    group: "backlight",
  },
  0x7802: {
    key: "QK_BACKLIGHT_TOGGLE",
    label: "Toggle Backlight",
    aliases: ["BL_TOGG"],
    group: "backlight",
  },
  0x7803: {
    key: "QK_BACKLIGHT_DOWN",
    label: "Backlight Down",
    aliases: ["BL_DOWN"],
    group: "backlight",
  },
  0x7804: { key: "QK_BACKLIGHT_UP", label: "Backlight Up", aliases: ["BL_UP"], group: "backlight" },
  0x7805: {
    key: "QK_BACKLIGHT_STEP",
    label: "Backlight Step",
    aliases: ["BL_STEP"],
    group: "backlight",
  },
  0x7806: {
    key: "QK_BACKLIGHT_TOGGLE_BREATHING",
    label: "Toggle Breathing",
    aliases: ["BL_BRTG"],
    group: "backlight",
  },
  0x7810: {
    key: "QK_LED_MATRIX_ON",
    label: "LED Matrix On",
    aliases: ["LM_ON"],
    group: "led_matrix",
  },
  0x7811: {
    key: "QK_LED_MATRIX_OFF",
    label: "LED Matrix Off",
    aliases: ["LM_OFF"],
    group: "led_matrix",
  },
  0x7812: {
    key: "QK_LED_MATRIX_TOGGLE",
    label: "Toggle LED Matrix",
    aliases: ["LM_TOGG"],
    group: "led_matrix",
  },
  0x7813: {
    key: "QK_LED_MATRIX_MODE_NEXT",
    label: "LED Matrix Next",
    aliases: ["LM_NEXT"],
    group: "led_matrix",
  },
  0x7814: {
    key: "QK_LED_MATRIX_MODE_PREVIOUS",
    label: "LED Matrix Previous",
    aliases: ["LM_PREV"],
    group: "led_matrix",
  },
  0x7815: {
    key: "QK_LED_MATRIX_BRIGHTNESS_UP",
    label: "LED Matrix Brightness Up",
    aliases: ["LM_BRIU"],
    group: "led_matrix",
  },
  0x7816: {
    key: "QK_LED_MATRIX_BRIGHTNESS_DOWN",
    label: "LED Matrix Brightness Down",
    aliases: ["LM_BRID"],
    group: "led_matrix",
  },
  0x7817: {
    key: "QK_LED_MATRIX_SPEED_UP",
    label: "LED Matrix Speed Up",
    aliases: ["LM_SPDU"],
    group: "led_matrix",
  },
  0x7818: {
    key: "QK_LED_MATRIX_SPEED_DOWN",
    label: "LED Matrix Speed Down",
    aliases: ["LM_SPDD"],
    group: "led_matrix",
  },
  0x7819: {
    key: "QK_LED_MATRIX_FLAG_NEXT",
    label: "LED Matrix Flag Next",
    aliases: ["LM_FLGN"],
    group: "led_matrix",
  },
  0x781a: {
    key: "QK_LED_MATRIX_FLAG_PREVIOUS",
    label: "LED Matrix Flag Previous",
    aliases: ["LM_FLGP"],
    group: "led_matrix",
  },
  0x7820: {
    key: "QK_UNDERGLOW_TOGGLE",
    label: "Toggle RGB Underglow",
    aliases: ["UG_TOGG"],
    group: "underglow",
  },
  0x7821: {
    key: "QK_UNDERGLOW_MODE_NEXT",
    label: "RGB Underglow Next",
    aliases: ["!reset!", "UG_NEXT"],
    group: "underglow",
  },
  0x7822: {
    key: "QK_UNDERGLOW_MODE_PREVIOUS",
    label: "RGB Underglow Previous",
    aliases: ["!reset!", "UG_PREV"],
    group: "underglow",
  },
  0x7823: {
    key: "QK_UNDERGLOW_HUE_UP",
    label: "RGB Underglow Hue Up",
    aliases: ["UG_HUEU"],
    group: "underglow",
  },
  0x7824: {
    key: "QK_UNDERGLOW_HUE_DOWN",
    label: "RGB Underglow Hue Down",
    aliases: ["UG_HUED"],
    group: "underglow",
  },
  0x7825: {
    key: "QK_UNDERGLOW_SATURATION_UP",
    label: "RGB Underglow Saturation Up",
    aliases: ["UG_SATU"],
    group: "underglow",
  },
  0x7826: {
    key: "QK_UNDERGLOW_SATURATION_DOWN",
    label: "RGB Underglow Saturation Down",
    aliases: ["UG_SATD"],
    group: "underglow",
  },
  0x7827: {
    key: "QK_UNDERGLOW_VALUE_UP",
    label: "RGB Underglow Value Up",
    aliases: ["UG_VALU"],
    group: "underglow",
  },
  0x7828: {
    key: "QK_UNDERGLOW_VALUE_DOWN",
    label: "RGB Underglow Value Down",
    aliases: ["UG_VALD"],
    group: "underglow",
  },
  0x7829: {
    key: "QK_UNDERGLOW_SPEED_UP",
    label: "RGB Underglow Speed Up",
    aliases: ["UG_SPDU"],
    group: "underglow",
  },
  0x782a: {
    key: "QK_UNDERGLOW_SPEED_DOWN",
    label: "RGB Underglow Speed Down",
    aliases: ["UG_SPDD"],
    group: "underglow",
  },
  0x782b: { key: "RGB_MODE_PLAIN", label: "Rgb Mode Plain", aliases: ["RGB_M_P"] },
  0x782c: { key: "RGB_MODE_BREATHE", label: "Rgb Mode Breathe", aliases: ["RGB_M_B"] },
  0x782d: { key: "RGB_MODE_RAINBOW", label: "Rgb Mode Rainbow", aliases: ["RGB_M_R"] },
  0x782e: { key: "RGB_MODE_SWIRL", label: "Rgb Mode Swirl", aliases: ["RGB_M_SW"] },
  0x782f: { key: "RGB_MODE_SNAKE", label: "Rgb Mode Snake", aliases: ["RGB_M_SN"] },
  0x7830: { key: "RGB_MODE_KNIGHT", label: "Rgb Mode Knight", aliases: ["RGB_M_K"] },
  0x7831: { key: "RGB_MODE_XMAS", label: "Rgb Mode Xmas", aliases: ["RGB_M_X"] },
  0x7832: { key: "RGB_MODE_GRADIENT", label: "Rgb Mode Gradient", aliases: ["RGB_M_G"] },
  0x7833: { key: "RGB_MODE_RGBTEST", label: "Rgb Mode Rgbtest", aliases: ["RGB_M_T"] },
  0x7834: { key: "RGB_MODE_TWINKLE", label: "Rgb Mode Twinkle", aliases: ["RGB_M_TW"] },
  0x7840: {
    key: "QK_RGB_MATRIX_ON",
    label: "RGB Matrix On",
    aliases: ["RM_ON"],
    group: "rgb_matrix",
  },
  0x7841: {
    key: "QK_RGB_MATRIX_OFF",
    label: "RGB Matrix Off",
    aliases: ["RM_OFF"],
    group: "rgb_matrix",
  },
  0x7842: {
    key: "QK_RGB_MATRIX_TOGGLE",
    label: "Toggle RGB Matrix",
    aliases: ["RM_TOGG"],
    group: "rgb_matrix",
  },
  0x7843: {
    key: "QK_RGB_MATRIX_MODE_NEXT",
    label: "RGB Matrix Next",
    aliases: ["RM_NEXT"],
    group: "rgb_matrix",
  },
  0x7844: {
    key: "QK_RGB_MATRIX_MODE_PREVIOUS",
    label: "RGB Matrix Previous",
    aliases: ["RM_PREV"],
    group: "rgb_matrix",
  },
  0x7845: {
    key: "QK_RGB_MATRIX_HUE_UP",
    label: "RGB Matrix Hue Up",
    aliases: ["RM_HUEU"],
    group: "rgb_matrix",
  },
  0x7846: {
    key: "QK_RGB_MATRIX_HUE_DOWN",
    label: "RGB Matrix Hue Down",
    aliases: ["RM_HUED"],
    group: "rgb_matrix",
  },
  0x7847: {
    key: "QK_RGB_MATRIX_SATURATION_UP",
    label: "RGB Matrix Saturation Up",
    aliases: ["RM_SATU"],
    group: "rgb_matrix",
  },
  0x7848: {
    key: "QK_RGB_MATRIX_SATURATION_DOWN",
    label: "RGB Matrix Saturation Down",
    aliases: ["RM_SATD"],
    group: "rgb_matrix",
  },
  0x7849: {
    key: "QK_RGB_MATRIX_VALUE_UP",
    label: "RGB Matrix Value Up",
    aliases: ["RM_VALU"],
    group: "rgb_matrix",
  },
  0x784a: {
    key: "QK_RGB_MATRIX_VALUE_DOWN",
    label: "RGB Matrix Value Down",
    aliases: ["RM_VALD"],
    group: "rgb_matrix",
  },
  0x784b: {
    key: "QK_RGB_MATRIX_SPEED_UP",
    label: "RGB Matrix Speed Up",
    aliases: ["RM_SPDU"],
    group: "rgb_matrix",
  },
  0x784c: {
    key: "QK_RGB_MATRIX_SPEED_DOWN",
    label: "RGB Matrix Speed Down",
    aliases: ["RM_SPDD"],
    group: "rgb_matrix",
  },
  0x784d: {
    key: "QK_RGB_MATRIX_FLAG_NEXT",
    label: "RGB Matrix Flag Next",
    aliases: ["RM_FLGN"],
    group: "rgb_matrix",
  },
  0x784e: {
    key: "QK_RGB_MATRIX_FLAG_PREVIOUS",
    label: "RGB Matrix Flag Previous",
    aliases: ["RM_FLGP"],
    group: "rgb_matrix",
  },
  0x7c00: { key: "QK_BOOTLOADER", label: "Bootloader", aliases: ["QK_BOOT"], group: "quantum" },
  0x7c01: { key: "QK_REBOOT", label: "Reboot", aliases: ["QK_RBT"], group: "quantum" },
  0x7c02: { key: "QK_DEBUG_TOGGLE", label: "Toggle Debug", aliases: ["DB_TOGG"], group: "quantum" },
  0x7c03: { key: "QK_CLEAR_EEPROM", label: "Clear EEPROM", aliases: ["EE_CLR"], group: "quantum" },
  0x7c04: { key: "QK_MAKE", label: "Make", aliases: [], group: "quantum" },
  0x7c10: {
    key: "QK_AUTO_SHIFT_DOWN",
    label: "Auto Shift Down",
    aliases: ["AS_DOWN"],
    group: "quantum",
  },
  0x7c11: { key: "QK_AUTO_SHIFT_UP", label: "Auto Shift Up", aliases: ["AS_UP"], group: "quantum" },
  0x7c12: {
    key: "QK_AUTO_SHIFT_REPORT",
    label: "Auto Shift Report",
    aliases: ["AS_RPT"],
    group: "quantum",
  },
  0x7c13: { key: "QK_AUTO_SHIFT_ON", label: "Auto Shift On", aliases: ["AS_ON"], group: "quantum" },
  0x7c14: {
    key: "QK_AUTO_SHIFT_OFF",
    label: "Auto Shift Off",
    aliases: ["AS_OFF"],
    group: "quantum",
  },
  0x7c15: {
    key: "QK_AUTO_SHIFT_TOGGLE",
    label: "Toggle Auto Shift",
    aliases: ["AS_TOGG"],
    group: "quantum",
  },
  0x7c16: { key: "QK_GRAVE_ESCAPE", label: "Grave Esc", aliases: ["QK_GESC"], group: "quantum" },
  0x7c17: { key: "QK_VELOCIKEY_TOGGLE", label: "Velocikey Toggle", aliases: ["VK_TOGG"] },
  0x7c18: {
    key: "QK_SPACE_CADET_LEFT_CTRL_PARENTHESIS_OPEN",
    label: "LCtl/(",
    aliases: ["SC_LCPO"],
    group: "quantum",
  },
  0x7c19: {
    key: "QK_SPACE_CADET_RIGHT_CTRL_PARENTHESIS_CLOSE",
    label: "RCtl/)",
    aliases: ["SC_RCPC"],
    group: "quantum",
  },
  0x7c1a: {
    key: "QK_SPACE_CADET_LEFT_SHIFT_PARENTHESIS_OPEN",
    label: "LSft/)",
    aliases: ["SC_LSPO"],
    group: "quantum",
  },
  0x7c1b: {
    key: "QK_SPACE_CADET_RIGHT_SHIFT_PARENTHESIS_CLOSE",
    label: "RSft/)",
    aliases: ["SC_RSPC"],
    group: "quantum",
  },
  0x7c1c: {
    key: "QK_SPACE_CADET_LEFT_ALT_PARENTHESIS_OPEN",
    label: "LAlt/(",
    aliases: ["SC_LAPO"],
    group: "quantum",
  },
  0x7c1d: {
    key: "QK_SPACE_CADET_RIGHT_ALT_PARENTHESIS_CLOSE",
    label: "RAlt/)",
    aliases: ["SC_RAPC"],
    group: "quantum",
  },
  0x7c1e: {
    key: "QK_SPACE_CADET_RIGHT_SHIFT_ENTER",
    label: "RSft/Ent",
    aliases: ["SC_SENT"],
    group: "quantum",
  },
  0x7c30: {
    key: "QK_UNICODE_MODE_NEXT",
    label: "Unicode Mode Next",
    aliases: ["UC_NEXT"],
    group: "quantum",
  },
  0x7c31: {
    key: "QK_UNICODE_MODE_PREVIOUS",
    label: "Unicode Mode Previous",
    aliases: ["UC_PREV"],
    group: "quantum",
  },
  0x7c32: {
    key: "QK_UNICODE_MODE_MACOS",
    label: "Unicode Mode macOS",
    aliases: ["UC_MAC"],
    group: "quantum",
  },
  0x7c33: {
    key: "QK_UNICODE_MODE_LINUX",
    label: "Unicode Mode Linux",
    aliases: ["UC_LINX"],
    group: "quantum",
  },
  0x7c34: {
    key: "QK_UNICODE_MODE_WINDOWS",
    label: "Unicode Mode Windows",
    aliases: ["UC_WIN"],
    group: "quantum",
  },
  0x7c35: {
    key: "QK_UNICODE_MODE_BSD",
    label: "Unicode Mode BSD",
    aliases: ["UC_BSD"],
    group: "quantum",
  },
  0x7c36: {
    key: "QK_UNICODE_MODE_WINCOMPOSE",
    label: "Unicode Mode WinCompose",
    aliases: ["UC_WINC"],
    group: "quantum",
  },
  0x7c37: {
    key: "QK_UNICODE_MODE_EMACS",
    label: "Unicode Mode emacs",
    aliases: ["UC_EMAC"],
    group: "quantum",
  },
  0x7c40: { key: "QK_HAPTIC_ON", label: "Haptic On", aliases: ["HF_ON"], group: "quantum" },
  0x7c41: { key: "QK_HAPTIC_OFF", label: "Haptic Off", aliases: ["HF_OFF"], group: "quantum" },
  0x7c42: {
    key: "QK_HAPTIC_TOGGLE",
    label: "Toggle Haptic",
    aliases: ["HF_TOGG"],
    group: "quantum",
  },
  0x7c43: { key: "QK_HAPTIC_RESET", label: "Haptic Reset", aliases: ["HF_RST"], group: "quantum" },
  0x7c44: {
    key: "QK_HAPTIC_FEEDBACK_TOGGLE",
    label: "Toggle Haptic Feedback",
    aliases: ["HF_FDBK"],
    group: "quantum",
  },
  0x7c45: {
    key: "QK_HAPTIC_BUZZ_TOGGLE",
    label: "Toggle Haptic Buzz",
    aliases: ["HF_BUZZ"],
    group: "quantum",
  },
  0x7c46: {
    key: "QK_HAPTIC_MODE_NEXT",
    label: "Haptic Mode Next",
    aliases: ["HF_NEXT"],
    group: "quantum",
  },
  0x7c47: {
    key: "QK_HAPTIC_MODE_PREVIOUS",
    label: "Haptic Mode Previous",
    aliases: ["HF_PREV"],
    group: "quantum",
  },
  0x7c48: {
    key: "QK_HAPTIC_CONTINUOUS_TOGGLE",
    label: "Toggle Haptic Continuous",
    aliases: ["HF_CONT"],
    group: "quantum",
  },
  0x7c49: {
    key: "QK_HAPTIC_CONTINUOUS_UP",
    label: "Haptic Continuous Up",
    aliases: ["HF_CONU"],
    group: "quantum",
  },
  0x7c4a: {
    key: "QK_HAPTIC_CONTINUOUS_DOWN",
    label: "Haptic Continuous Down",
    aliases: ["HF_COND"],
    group: "quantum",
  },
  0x7c4b: {
    key: "QK_HAPTIC_DWELL_UP",
    label: "Haptic Dwell Up",
    aliases: ["HF_DWLU"],
    group: "quantum",
  },
  0x7c4c: {
    key: "QK_HAPTIC_DWELL_DOWN",
    label: "Haptic Dwell Down",
    aliases: ["HF_DWLD"],
    group: "quantum",
  },
  0x7c50: { key: "QK_COMBO_ON", label: "Combo On", aliases: ["CM_ON"], group: "quantum" },
  0x7c51: { key: "QK_COMBO_OFF", label: "Combo Off", aliases: ["CM_OFF"], group: "quantum" },
  0x7c52: { key: "QK_COMBO_TOGGLE", label: "Toggle Combo", aliases: ["CM_TOGG"], group: "quantum" },
  0x7c53: {
    key: "QK_DYNAMIC_MACRO_RECORD_START_1",
    label: "Dynamic Macro Record 1",
    aliases: ["DM_REC1"],
    group: "quantum",
  },
  0x7c54: {
    key: "QK_DYNAMIC_MACRO_RECORD_START_2",
    label: "Dynamic Macro Record 2",
    aliases: ["DM_REC2"],
    group: "quantum",
  },
  0x7c55: {
    key: "QK_DYNAMIC_MACRO_RECORD_STOP",
    label: "Dynamic Macro Stop Recording",
    aliases: ["DM_RSTP"],
    group: "quantum",
  },
  0x7c56: {
    key: "QK_DYNAMIC_MACRO_PLAY_1",
    label: "Dynamic Macro Play 1",
    aliases: ["DM_PLY1"],
    group: "quantum",
  },
  0x7c57: {
    key: "QK_DYNAMIC_MACRO_PLAY_2",
    label: "Dynamic Macro Play 2",
    aliases: ["DM_PLY2"],
    group: "quantum",
  },
  0x7c58: { key: "QK_LEADER", label: "Leader", aliases: ["QK_LEAD"], group: "quantum" },
  0x7c59: { key: "QK_LOCK", label: "Lock", aliases: [], group: "quantum" },
  0x7c5a: { key: "QK_ONE_SHOT_ON", label: "One Shot On", aliases: ["OS_ON"], group: "quantum" },
  0x7c5b: { key: "QK_ONE_SHOT_OFF", label: "One Shot Off", aliases: ["OS_OFF"], group: "quantum" },
  0x7c5c: {
    key: "QK_ONE_SHOT_TOGGLE",
    label: "Toggle One Shot",
    aliases: ["OS_TOGG"],
    group: "quantum",
  },
  0x7c5d: {
    key: "QK_KEY_OVERRIDE_TOGGLE",
    label: "Toggle Key Overrides",
    aliases: ["KO_TOGG"],
    group: "quantum",
  },
  0x7c5e: {
    key: "QK_KEY_OVERRIDE_ON",
    label: "Key Overrides On",
    aliases: ["KO_ON"],
    group: "quantum",
  },
  0x7c5f: {
    key: "QK_KEY_OVERRIDE_OFF",
    label: "Key Overrides Off",
    aliases: ["KO_OFF"],
    group: "quantum",
  },
  0x7c60: { key: "QK_SECURE_LOCK", label: "Lock", aliases: ["SE_LOCK"], group: "quantum" },
  0x7c61: { key: "QK_SECURE_UNLOCK", label: "Unlock", aliases: ["SE_UNLK"], group: "quantum" },
  0x7c62: { key: "QK_SECURE_TOGGLE", label: "Toggle Lock", aliases: ["SE_TOGG"], group: "quantum" },
  0x7c63: {
    key: "QK_SECURE_REQUEST",
    label: "Request Unlock",
    aliases: ["SE_REQ"],
    group: "quantum",
  },
  0x7c70: {
    key: "QK_DYNAMIC_TAPPING_TERM_PRINT",
    label: "Print Dynamic Tapping Term",
    aliases: ["DT_PRNT"],
    group: "quantum",
  },
  0x7c71: {
    key: "QK_DYNAMIC_TAPPING_TERM_UP",
    label: "Dynamic Tapping Term Up",
    aliases: ["DT_UP"],
    group: "quantum",
  },
  0x7c72: {
    key: "QK_DYNAMIC_TAPPING_TERM_DOWN",
    label: "Dynamic Tapping Term Down",
    aliases: ["DT_DOWN"],
    group: "quantum",
  },
  0x7c73: {
    key: "QK_CAPS_WORD_TOGGLE",
    label: "Toggle Caps Word",
    aliases: ["CW_TOGG"],
    group: "quantum",
  },
  0x7c74: {
    key: "QK_AUTOCORRECT_ON",
    label: "Autocorrect On",
    aliases: ["AC_ON"],
    group: "quantum",
  },
  0x7c75: {
    key: "QK_AUTOCORRECT_OFF",
    label: "Autocorrect Off",
    aliases: ["AC_OFF"],
    group: "quantum",
  },
  0x7c76: {
    key: "QK_AUTOCORRECT_TOGGLE",
    label: "Toggle Autocorrect",
    aliases: ["AC_TOGG"],
    group: "quantum",
  },
  0x7c77: { key: "QK_TRI_LAYER_LOWER", label: "Lower", aliases: ["TL_LOWR"], group: "quantum" },
  0x7c78: { key: "QK_TRI_LAYER_UPPER", label: "Upper", aliases: ["TL_UPPR"], group: "quantum" },
  0x7c79: { key: "QK_REPEAT_KEY", label: "Repeat", aliases: ["QK_REP"], group: "quantum" },
  0x7c7a: {
    key: "QK_ALT_REPEAT_KEY",
    label: "Repeat Alternate",
    aliases: ["QK_AREP"],
    group: "quantum",
  },
  0x7c7b: { key: "QK_LAYER_LOCK", label: "Layer Lock", aliases: ["QK_LLCK"], group: "quantum" },
  0x7e00: { key: "QK_KB_0", label: "Keyboard 0", aliases: [], group: "kb" },
  0x7e01: { key: "QK_KB_1", label: "Keyboard 1", aliases: [], group: "kb" },
  0x7e02: { key: "QK_KB_2", label: "Keyboard 2", aliases: [], group: "kb" },
  0x7e03: { key: "QK_KB_3", label: "Keyboard 3", aliases: [], group: "kb" },
  0x7e04: { key: "QK_KB_4", label: "Keyboard 4", aliases: [], group: "kb" },
  0x7e05: { key: "QK_KB_5", label: "Keyboard 5", aliases: [], group: "kb" },
  0x7e06: { key: "QK_KB_6", label: "Keyboard 6", aliases: [], group: "kb" },
  0x7e07: { key: "QK_KB_7", label: "Keyboard 7", aliases: [], group: "kb" },
  0x7e08: { key: "QK_KB_8", label: "Keyboard 8", aliases: [], group: "kb" },
  0x7e09: { key: "QK_KB_9", label: "Keyboard 9", aliases: [], group: "kb" },
  0x7e0a: { key: "QK_KB_10", label: "Keyboard 10", aliases: [], group: "kb" },
  0x7e0b: { key: "QK_KB_11", label: "Keyboard 11", aliases: [], group: "kb" },
  0x7e0c: { key: "QK_KB_12", label: "Keyboard 12", aliases: [], group: "kb" },
  0x7e0d: { key: "QK_KB_13", label: "Keyboard 13", aliases: [], group: "kb" },
  0x7e0e: { key: "QK_KB_14", label: "Keyboard 14", aliases: [], group: "kb" },
  0x7e0f: { key: "QK_KB_15", label: "Keyboard 15", aliases: [], group: "kb" },
  0x7e10: { key: "QK_KB_16", label: "Keyboard 16", aliases: [], group: "kb" },
  0x7e11: { key: "QK_KB_17", label: "Keyboard 17", aliases: [], group: "kb" },
  0x7e12: { key: "QK_KB_18", label: "Keyboard 18", aliases: [], group: "kb" },
  0x7e13: { key: "QK_KB_19", label: "Keyboard 19", aliases: [], group: "kb" },
  0x7e14: { key: "QK_KB_20", label: "Keyboard 20", aliases: [], group: "kb" },
  0x7e15: { key: "QK_KB_21", label: "Keyboard 21", aliases: [], group: "kb" },
  0x7e16: { key: "QK_KB_22", label: "Keyboard 22", aliases: [], group: "kb" },
  0x7e17: { key: "QK_KB_23", label: "Keyboard 23", aliases: [], group: "kb" },
  0x7e18: { key: "QK_KB_24", label: "Keyboard 24", aliases: [], group: "kb" },
  0x7e19: { key: "QK_KB_25", label: "Keyboard 25", aliases: [], group: "kb" },
  0x7e1a: { key: "QK_KB_26", label: "Keyboard 26", aliases: [], group: "kb" },
  0x7e1b: { key: "QK_KB_27", label: "Keyboard 27", aliases: [], group: "kb" },
  0x7e1c: { key: "QK_KB_28", label: "Keyboard 28", aliases: [], group: "kb" },
  0x7e1d: { key: "QK_KB_29", label: "Keyboard 29", aliases: [], group: "kb" },
  0x7e1e: { key: "QK_KB_30", label: "Keyboard 30", aliases: [], group: "kb" },
  0x7e1f: { key: "QK_KB_31", label: "Keyboard 31", aliases: [], group: "kb" },
  0x7e40: { key: "QK_USER_0", label: "User 0", aliases: [], group: "user" },
  0x7e41: { key: "QK_USER_1", label: "User 1", aliases: [], group: "user" },
  0x7e42: { key: "QK_USER_2", label: "User 2", aliases: [], group: "user" },
  0x7e43: { key: "QK_USER_3", label: "User 3", aliases: [], group: "user" },
  0x7e44: { key: "QK_USER_4", label: "User 4", aliases: [], group: "user" },
  0x7e45: { key: "QK_USER_5", label: "User 5", aliases: [], group: "user" },
  0x7e46: { key: "QK_USER_6", label: "User 6", aliases: [], group: "user" },
  0x7e47: { key: "QK_USER_7", label: "User 7", aliases: [], group: "user" },
  0x7e48: { key: "QK_USER_8", label: "User 8", aliases: [], group: "user" },
  0x7e49: { key: "QK_USER_9", label: "User 9", aliases: [], group: "user" },
  0x7e4a: { key: "QK_USER_10", label: "User 10", aliases: [], group: "user" },
  0x7e4b: { key: "QK_USER_11", label: "User 11", aliases: [], group: "user" },
  0x7e4c: { key: "QK_USER_12", label: "User 12", aliases: [], group: "user" },
  0x7e4d: { key: "QK_USER_13", label: "User 13", aliases: [], group: "user" },
  0x7e4e: { key: "QK_USER_14", label: "User 14", aliases: [], group: "user" },
  0x7e4f: { key: "QK_USER_15", label: "User 15", aliases: [], group: "user" },
  0x7e50: { key: "QK_USER_16", label: "User 16", aliases: [], group: "user" },
  0x7e51: { key: "QK_USER_17", label: "User 17", aliases: [], group: "user" },
  0x7e52: { key: "QK_USER_18", label: "User 18", aliases: [], group: "user" },
  0x7e53: { key: "QK_USER_19", label: "User 19", aliases: [], group: "user" },
  0x7e54: { key: "QK_USER_20", label: "User 20", aliases: [], group: "user" },
  0x7e55: { key: "QK_USER_21", label: "User 21", aliases: [], group: "user" },
  0x7e56: { key: "QK_USER_22", label: "User 22", aliases: [], group: "user" },
  0x7e57: { key: "QK_USER_23", label: "User 23", aliases: [], group: "user" },
  0x7e58: { key: "QK_USER_24", label: "User 24", aliases: [], group: "user" },
  0x7e59: { key: "QK_USER_25", label: "User 25", aliases: [], group: "user" },
  0x7e5a: { key: "QK_USER_26", label: "User 26", aliases: [], group: "user" },
  0x7e5b: { key: "QK_USER_27", label: "User 27", aliases: [], group: "user" },
  0x7e5c: { key: "QK_USER_28", label: "User 28", aliases: [], group: "user" },
  0x7e5d: { key: "QK_USER_29", label: "User 29", aliases: [], group: "user" },
  0x7e5e: { key: "QK_USER_30", label: "User 30", aliases: [], group: "user" },
  0x7e5f: { key: "QK_USER_31", label: "User 31", aliases: [], group: "user" },
};

export const qmkDirectKeycodeValues: Record<string, number> = Object.fromEntries(
  Object.entries(qmkDirectKeycodes).flatMap(([value, info]) => {
    const numericValue = Number(value);
    return [
      [info.key, numericValue],
      ...info.aliases.map((alias) => [alias, numericValue] as const),
    ];
  }),
);
