/**
 * Local VIA-style keyboard overrides. These are merged into the live catalog
 * fetched from the-via/keyboards so we can ship layouts the upstream repo
 * doesn't carry (or carries incorrectly). They share the same JSON shape as
 * upstream VIA v3 definitions, so the existing parser handles them as-is.
 *
 * Add a new entry by:
 *   1. Drop a `{ sourcePath, json }` record below.
 *   2. `sourcePath` is the slug used by the catalog's id system (no `.json`).
 *   3. Give it a `priority` boost so it ranks above any conflicting upstream
 *      entry — the catalog picker sorts by priority then name.
 */
export interface LocalKeyboardDefinition {
  /** Pseudo-path used for catalog id + display. */
  sourcePath: string;
  /** Priority boost above the upstream scorer. Higher = ranks first. */
  priority: number;
  /** A VIA v3 JSON definition. */
  json: Record<string, unknown>;
}

/**
 * Bastardkb Dilemma 3x5+2 — v1 PCB with two thumbs per side and no encoder
 * position. VIA's upstream repo only ships `3x5_3` (three thumbs); this
 * fills the gap.
 *
 * Matrix mapping is taken verbatim from QMK's canonical info.json
 * (`keyboards/bastardkb/dilemma/3x5_2/info.json`):
 *
 *     Left thumbs:  (3,0) outer · (3,2) inner
 *     Right thumbs: (7,2) inner · (7,0) outer
 *
 * Right half columns are matrix-reversed (col 4 = leftmost physical key)
 * because Bastardkb wires the split halves through one shared matrix.
 *
 * Vendor / product IDs match the QMK firmware's PID 0x1835 so a Dilemma
 * 3x5+2 auto-attaches and picks this layout instead of the v2 (3x5_3) one.
 */
const dilemma3x5_2: LocalKeyboardDefinition = {
  sourcePath: "klakson/bastardkb/dilemma/3x5_2/dilemma_3x5_2",
  priority: 6000,
  json: {
    name: "Dilemma 3x5+2",
    vendorId: "0xA8F8",
    productId: "0x1835",
    matrix: { rows: 8, cols: 5 },
    menus: ["qmk_rgb_matrix"],
    layouts: {
      // --- Generated by `scripts/normalize-dilemma.mjs` from a photo of
      //     a real Dilemma 3x5+2. Layout is forced to the canonical
      //     Bastardkb Dilemma 3x5 spec: 1u column spacing, stagger
      //     [0.93, 0.31, 0, 0.28, 0.42] pinky→inner, and zero per-column
      //     splay (the PCB is flat — the small ±°detected angles were
      //     photo wobble). Right half's ~39° photo tilt is stripped so
      //     both halves render flat side-by-side with a 3u inter-half
      //     gap (`0,2` center at (2,0); `4,2` center at (10,0)). Thumbs
      //     keep their measured angles in the standard Bastardkb sign
      //     convention: left CW (+), right CCW (−). ---
      keymap: [
        [{ r: 0, rx: 0, ry: 0.93, x: 0, y: 0 }, "0,0"],
        [{ r: 0, rx: 1, ry: 0.31, x: 0, y: 0 }, "0,1"],
        [{ r: 0, rx: 2, ry: 0, x: 0, y: 0 }, "0,2"],
        [{ r: 0, rx: 3, ry: 0.28, x: 0, y: 0 }, "0,3"],
        [{ r: 0, rx: 4, ry: 0.42, x: 0, y: 0 }, "0,4"],
        [{ r: 0, rx: 0, ry: 1.93, x: 0, y: 0 }, "1,0"],
        [{ r: 0, rx: 1, ry: 1.31, x: 0, y: 0 }, "1,1"],
        [{ r: 0, rx: 2, ry: 1, x: 0, y: 0 }, "1,2"],
        [{ r: 0, rx: 3, ry: 1.28, x: 0, y: 0 }, "1,3"],
        [{ r: 0, rx: 4, ry: 1.42, x: 0, y: 0 }, "1,4"],
        [{ r: 0, rx: 0, ry: 2.93, x: 0, y: 0 }, "2,0"],
        [{ r: 0, rx: 1, ry: 2.31, x: 0, y: 0 }, "2,1"],
        [{ r: 0, rx: 2, ry: 2, x: 0, y: 0 }, "2,2"],
        [{ r: 0, rx: 3, ry: 2.28, x: 0, y: 0 }, "2,3"],
        [{ r: 0, rx: 4, ry: 2.42, x: 0, y: 0 }, "2,4"],
        [{ r: 16.75, rx: 3.635, ry: 3.307, x: 0, y: 0 }, "3,0"],
        [{ r: 29.25, rx: 4.818, ry: 3.679, x: 0, y: 0 }, "3,2"],
        [{ r: 0, rx: 12, ry: 0.93, x: 0, y: 0 }, "4,0"],
        [{ r: 0, rx: 11, ry: 0.31, x: 0, y: 0 }, "4,1"],
        [{ r: 0, rx: 10, ry: 0, x: 0, y: 0 }, "4,2"],
        [{ r: 0, rx: 9, ry: 0.28, x: 0, y: 0 }, "4,3"],
        [{ r: 0, rx: 8, ry: 0.42, x: 0, y: 0 }, "4,4"],
        [{ r: 0, rx: 12, ry: 1.93, x: 0, y: 0 }, "5,0"],
        [{ r: 0, rx: 11, ry: 1.31, x: 0, y: 0 }, "5,1"],
        [{ r: 0, rx: 10, ry: 1, x: 0, y: 0 }, "5,2"],
        [{ r: 0, rx: 9, ry: 1.28, x: 0, y: 0 }, "5,3"],
        [{ r: 0, rx: 8, ry: 1.42, x: 0, y: 0 }, "5,4"],
        [{ r: 0, rx: 12, ry: 2.93, x: 0, y: 0 }, "6,0"],
        [{ r: 0, rx: 11, ry: 2.31, x: 0, y: 0 }, "6,1"],
        [{ r: 0, rx: 10, ry: 2, x: 0, y: 0 }, "6,2"],
        [{ r: 0, rx: 9, ry: 2.28, x: 0, y: 0 }, "6,3"],
        [{ r: 0, rx: 8, ry: 2.42, x: 0, y: 0 }, "6,4"],
        [{ r: -17, rx: 8.526, ry: 3.538, x: 0, y: 0 }, "7,0"],
        [{ r: -30.25, rx: 7.456, ry: 4.12, x: 0, y: 0 }, "7,2"],
      ],
    },
    customKeycodes: [
      { title: "Default DPI Increase", name: "DPI_INC", shortName: "DPI+" },
      { title: "Default DPI Decrease", name: "DPI_DEC", shortName: "DPI-" },
      { title: "Drag-scroll Toggle", name: "DRAG_TOG", shortName: "DrgT" },
    ],
    layers: [
      {
        id: "base",
        name: "Base",
        bindings: {
          "k0-0": "KC_Q",
          "k0-1": "KC_W",
          "k0-2": "KC_E",
          "k0-3": "KC_R",
          "k0-4": "KC_T",
          "k1-0": "KC_A",
          "k1-1": "KC_S",
          "k1-2": "KC_D",
          "k1-3": "KC_F",
          "k1-4": "KC_G",
          "k2-0": "KC_Z",
          "k2-1": "KC_X",
          "k2-2": "KC_C",
          "k2-3": "KC_V",
          "k2-4": "KC_B",
          "k3-0": "OSL(1)",
          "k3-2": "KC_SPC",
          "k4-0": "KC_P",
          "k4-1": "KC_O",
          "k4-2": "KC_I",
          "k4-3": "KC_U",
          "k4-4": "KC_Y",
          "k5-0": "KC_QUOT",
          "k5-1": "KC_L",
          "k5-2": "KC_K",
          "k5-3": "KC_J",
          "k5-4": "KC_H",
          "k6-0": "KC_SLSH",
          "k6-1": "KC_DOT",
          "k6-2": "KC_COMM",
          "k6-3": "KC_M",
          "k6-4": "KC_N",
          "k7-0": "OSL(2)",
          "k7-2": "KC_ENT",
        },
      },
      {
        id: "layer-1",
        name: "Numeral",
        bindings: {
          "k0-0": "KC_F1",
          "k0-1": "KC_F2",
          "k0-2": "KC_F3",
          "k0-3": "KC_F4",
          "k0-4": "KC_F5",
          "k1-0": "KC_F6",
          "k1-1": "KC_F7",
          "k1-2": "KC_F8",
          "k1-3": "KC_F9",
          "k1-4": "KC_F10",
          "k2-0": "KC_F11",
          "k2-1": "KC_F12",
          "k2-2": "QK_REP",
          "k2-3": "QK_AREP",
          "k2-4": "CW_TOGG",
          "k3-0": "KC_NO",
          "k3-2": "KC_TRNS",
          "k4-0": "KC_MINS",
          "k4-1": "KC_9",
          "k4-2": "KC_8",
          "k4-3": "KC_7",
          "k4-4": "KC_SLSH",
          "k5-0": "KC_PLUS",
          "k5-1": "KC_6",
          "k5-2": "KC_5",
          "k5-3": "KC_4",
          "k5-4": "KC_ASTR",
          "k6-0": "KC_DOT",
          "k6-1": "KC_3",
          "k6-2": "KC_2",
          "k6-3": "KC_1",
          "k6-4": "KC_EQL",
          "k7-0": "KC_0",
          "k7-2": "KC_TRNS",
        },
      },
      {
        id: "layer-2",
        name: "Symbols",
        bindings: {
          "k0-0": "KC_EXLM",
          "k0-1": "KC_AT",
          "k0-2": "KC_HASH",
          "k0-3": "KC_DLR",
          "k0-4": "KC_PERC",
          "k1-0": "KC_LABK",
          "k1-1": "KC_LCBR",
          "k1-2": "KC_LBRC",
          "k1-3": "KC_LPRN",
          "k1-4": "KC_MINS",
          "k2-0": "KC_BSLS",
          "k2-1": "KC_PIPE",
          "k2-2": "KC_UNDS",
          "k2-3": "KC_PLUS",
          "k2-4": "KC_NO",
          "k3-0": "KC_TRNS",
          "k3-2": "KC_TRNS",
          "k4-0": "KC_GRV",
          "k4-1": "KC_TILD",
          "k4-2": "KC_ASTR",
          "k4-3": "KC_AMPR",
          "k4-4": "KC_CIRC",
          "k5-0": "KC_RABK",
          "k5-1": "KC_RCBR",
          "k5-2": "KC_RBRC",
          "k5-3": "KC_RPRN",
          "k5-4": "KC_EQL",
          "k6-0": "KC_QUES",
          "k6-1": "KC_SCLN",
          "k6-2": "KC_COLN",
          "k6-3": "KC_SLSH",
          "k6-4": "KC_NO",
          "k7-0": "OSL(3)",
          "k7-2": "KC_TRNS",
        },
      },
      {
        id: "layer-3",
        name: "Navigation",
        bindings: {
          "k0-0": "TO(0)",
          "k0-1": "KC_VOLD",
          "k0-2": "KC_MUTE",
          "k0-3": "KC_VOLU",
          "k0-4": "KC_NO",
          "k1-0": "KC_LGUI",
          "k1-1": "KC_LALT",
          "k1-2": "KC_LCTL",
          "k1-3": "KC_LSFT",
          "k1-4": "KC_NO",
          "k2-0": "C(KC_Z)",
          "k2-1": "C(KC_X)",
          "k2-2": "C(KC_C)",
          "k2-3": "C(KC_V)",
          "k2-4": "KC_NO",
          "k3-0": "KC_TRNS",
          "k3-2": "KC_TRNS",
          "k4-0": "TO(0)",
          "k4-1": "KC_NO",
          "k4-2": "KC_NO",
          "k4-3": "KC_NO",
          "k4-4": "KC_NO",
          "k5-0": "KC_NO",
          "k5-1": "KC_RGHT",
          "k5-2": "KC_UP",
          "k5-3": "KC_DOWN",
          "k5-4": "KC_LEFT",
          "k6-0": "KC_NO",
          "k6-1": "KC_END",
          "k6-2": "KC_PGUP",
          "k6-3": "KC_PGDN",
          "k6-4": "KC_HOME",
          "k7-0": "KC_BSPC",
          "k7-2": "KC_ENT",
        },
      },
      {
        id: "layer-4",
        name: "Pointer",
        bindings: {
          "k0-0": "QK_BOOT",
          "k0-1": "KC_NO",
          "k0-2": "KC_NO",
          "k0-3": "DPI_MOD",
          "k0-4": "S_D_MOD",
          "k1-0": "KC_LGUI",
          "k1-1": "KC_LALT",
          "k1-2": "KC_LCTL",
          "k1-3": "KC_LSFT",
          "k1-4": "KC_NO",
          "k2-0": "KC_TRNS",
          "k2-1": "DRGSCRL",
          "k2-2": "SNIPING",
          "k2-3": "KC_BTN3",
          "k2-4": "KC_NO",
          "k3-0": "KC_BTN2",
          "k3-2": "KC_BTN1",
          "k4-0": "QK_BOOT",
          "k4-1": "KC_NO",
          "k4-2": "KC_NO",
          "k4-3": "DPI_MOD",
          "k4-4": "S_D_MOD",
          "k5-0": "KC_RGUI",
          "k5-1": "KC_RALT",
          "k5-2": "KC_RCTL",
          "k5-3": "KC_RSFT",
          "k5-4": "KC_NO",
          "k6-0": "KC_TRNS",
          "k6-1": "DRGSCRL",
          "k6-2": "SNIPING",
          "k6-3": "KC_BTN3",
          "k6-4": "KC_NO",
          "k7-0": "KC_BTN2",
          "k7-2": "KC_BTN1",
        },
      },
    ],
    combos: [
      {
        id: "qw-esc",
        name: "QW Esc",
        keys: ["k0-0", "k0-1"],
        binding: "KC_ESC",
        layerIds: ["base"],
      },
      {
        id: "er-tab",
        name: "ER Tab",
        keys: ["k0-2", "k0-3"],
        binding: "KC_TAB",
        layerIds: ["base"],
      },
      {
        id: "ui-del",
        name: "UI Delete",
        keys: ["k4-3", "k4-2"],
        binding: "KC_DEL",
        layerIds: ["base"],
      },
      {
        id: "op-bspc",
        name: "OP Backspace",
        keys: ["k4-1", "k4-0"],
        binding: "KC_BSPC",
        layerIds: ["base"],
      },
      {
        id: "qp-base",
        name: "QP Base reset",
        keys: ["k0-0", "k4-0"],
        binding: "TO(LAYER_BASE)",
        layerIds: ["base"],
      },
      {
        id: "qp-base-num",
        name: "QP Base reset (Num)",
        keys: ["k0-0", "k4-0"],
        binding: "TO(LAYER_BASE)",
        layerIds: ["layer-1"],
      },
      {
        id: "qp-base-sym",
        name: "QP Base reset (Sym)",
        keys: ["k0-0", "k4-0"],
        binding: "TO(LAYER_BASE)",
        layerIds: ["layer-2"],
      },
      {
        id: "as-shift",
        name: "AS Shift",
        keys: ["k1-0", "k1-1"],
        binding: "OSM(MOD_LSFT)",
        layerIds: ["base"],
      },
      {
        id: "sd-ctrl",
        name: "SD Ctrl",
        keys: ["k1-1", "k1-2"],
        binding: "OSM(MOD_LCTL)",
        layerIds: ["base"],
      },
      {
        id: "df-alt",
        name: "DF Alt",
        keys: ["k1-2", "k1-3"],
        binding: "OSM(MOD_LALT)",
        layerIds: ["base"],
      },
      {
        id: "asd-gui",
        name: "ASD Gui",
        keys: ["k1-0", "k1-1", "k1-2"],
        binding: "OSM(MOD_LGUI)",
        layerIds: ["base"],
      },
      {
        id: "zc-meh",
        name: "ZC Meh",
        keys: ["k2-0", "k2-2"],
        binding: "OSM(MOD_MEH)",
        layerIds: ["base"],
      },
      {
        id: "lquot-shift",
        name: "L Quote Shift",
        keys: ["k5-1", "k5-0"],
        binding: "OSM(MOD_RSFT)",
        layerIds: ["base"],
      },
      {
        id: "kl-ctrl",
        name: "KL Ctrl",
        keys: ["k5-2", "k5-1"],
        binding: "OSM(MOD_RCTL)",
        layerIds: ["base"],
      },
      {
        id: "jk-alt",
        name: "JK Alt",
        keys: ["k5-3", "k5-2"],
        binding: "OSM(MOD_RALT)",
        layerIds: ["base"],
      },
      {
        id: "klq-gui",
        name: "KL Quote Gui",
        keys: ["k5-2", "k5-1", "k5-0"],
        binding: "OSM(MOD_RGUI)",
        layerIds: ["base"],
      },
      {
        id: "comslsh-meh",
        name: "Comma Slash Meh",
        keys: ["k6-2", "k6-0"],
        binding: "OSM(MOD_MEH)",
        layerIds: ["base"],
      },
    ],
  },
};

export const localKeyboardDefinitions: LocalKeyboardDefinition[] = [dilemma3x5_2];
