/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/cloudflare.d.ts --include-runtime false` (hash: 65e94dc109a2bf8d07a04ed856ba3453)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: unknown;
    durableNamespaces: "UserWorkbenchAgent" | "AuthAgent" | "LiveStoreSyncDO";
  }
  interface Env {
    ASSETS: Fetcher;
    UserWorkbenchAgent: DurableObjectNamespace<
      import("./agents/user-workbench").UserWorkbenchAgent
    >;
    AuthAgent: DurableObjectNamespace<import("./agents/auth-agent").AuthAgent>;
    // Hand-written until `wrangler types` regenerates this file:
    // `makeDurableObject(...)` returns an anonymous class so we
    // type-ref the module export.
    LiveStoreSyncDO: DurableObjectNamespace<
      InstanceType<typeof import("./agents/livestore-sync").LiveStoreSyncDO>
    >;
  }
}
interface Env extends Cloudflare.Env {}
