/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/cloudflare.d.ts --include-runtime false` (hash: 65e94dc109a2bf8d07a04ed856ba3453)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: unknown;
    durableNamespaces: "UserWorkbenchAgent" | "AuthAgent";
  }
  interface Env {
    ASSETS: Fetcher;
    UserWorkbenchAgent: DurableObjectNamespace<
      import("./agents/user-workbench").UserWorkbenchAgent
    >;
    AuthAgent: DurableObjectNamespace<import("./agents/auth-agent").AuthAgent>;
  }
}
interface Env extends Cloudflare.Env {}
